// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package filehandling.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import filehandling.FileHandling;

public class StringFromURL extends CustomJavaAction<java.lang.String>
{
	private java.lang.String url;

	public StringFromURL(IContext context, java.lang.String url)
	{
		super(context);
		this.url = url;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		return FileHandling.readStringFromURL(url);
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "StringFromURL";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
