// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package taskqueuehelpers.actions;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.connectionbus.data.IDataTable;
import com.mendix.systemwideinterfaces.connectionbus.requests.types.IOQLTextGetRequest;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import system.proxies.ProcessedQueueTask;
import system.proxies.QueueTaskStatus;
import taskqueuehelpers.proxies.ProcessedQueueCount;
import java.util.stream.Collectors;

/**
 * Creates a List of ProcessedQueueCount entities grouped by queue name. The grouping will aggregate the comlpeted and non-completed count of each queue based on status.
 */
public class GetProcessedQueueCount extends CustomJavaAction<java.util.List<IMendixObject>>
{
	public GetProcessedQueueCount(IContext context)
	{
		super(context);
	}

	@java.lang.Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		// BEGIN USER CODE
		final IContext ctx = getContext();

		final IOQLTextGetRequest request = Core.createOQLTextGetRequest();
		request.setQuery(QUERY);
		final IDataTable allTasks = Core.retrieveOQLDataTable(ctx, request);

		return allTasks.getRows().stream().map(row -> {
			final ProcessedQueueCount count = new ProcessedQueueCount(ctx);
			count.setQueueName(row.getValue(ctx, 0));
			count.setCompletedCount(row.getValue(ctx, 1));
			count.setUncompletedCount(row.getValue(ctx, 2));
			return count.getMendixObject();
		}).collect(Collectors.toList());
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetProcessedQueueCount";
	}

	// BEGIN EXTRA CODE
	private static final String QUERY = String.format(
			"select %s, %s, %s from %s group by %s",
			ProcessedQueueTask.MemberNames.QueueName,
			completedCount("="),
			completedCount("!="),
			ProcessedQueueTask.entityName,
			ProcessedQueueTask.MemberNames.QueueName);

	private static String completedCount(String comparison) {
		return String.format(
				"sum(case when %s %s '%s' then cast(1 as long) else cast(0 as long) end)",
				ProcessedQueueTask.MemberNames.Status,
				comparison,
				QueueTaskStatus.Completed);
	}
	// END EXTRA CODE
}
