// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package workflowcommons.proxies;

public class AssignmentHelper implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject assignmentHelperMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "WorkflowCommons.AssignmentHelper";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		IsAssignedUser("IsAssignedUser");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public AssignmentHelper(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected AssignmentHelper(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject assignmentHelperMendixObject)
	{
		if (assignmentHelperMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, assignmentHelperMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.assignmentHelperMendixObject = assignmentHelperMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static workflowcommons.proxies.AssignmentHelper initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new workflowcommons.proxies.AssignmentHelper(context, mendixObject);
	}

	public static workflowcommons.proxies.AssignmentHelper load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return workflowcommons.proxies.AssignmentHelper.initialize(context, mendixObject);
	}

	/**
	 * @return value of IsAssignedUser
	 */
	public final java.lang.Boolean getIsAssignedUser()
	{
		return getIsAssignedUser(getContext());
	}

	/**
	 * @param context
	 * @return value of IsAssignedUser
	 */
	public final java.lang.Boolean getIsAssignedUser(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsAssignedUser.toString());
	}

	/**
	 * Set value of IsAssignedUser
	 * @param isassigneduser
	 */
	public final void setIsAssignedUser(java.lang.Boolean isassigneduser)
	{
		setIsAssignedUser(getContext(), isassigneduser);
	}

	/**
	 * Set value of IsAssignedUser
	 * @param context
	 * @param isassigneduser
	 */
	public final void setIsAssignedUser(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean isassigneduser)
	{
		getMendixObject().setValue(context, MemberNames.IsAssignedUser.toString(), isassigneduser);
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return assignmentHelperMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final workflowcommons.proxies.AssignmentHelper that = (workflowcommons.proxies.AssignmentHelper) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
