// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package workflowcommons.proxies;

public class CleanupHelper implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject cleanupHelperMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "WorkflowCommons.CleanupHelper";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		TotalCount("TotalCount"),
		WorkflowName("WorkflowName"),
		StartDateStart("StartDateStart"),
		StartDateEnd("StartDateEnd"),
		EndDateStart("EndDateStart"),
		EndDateEnd("EndDateEnd"),
		IncludeCompleted("IncludeCompleted"),
		IncludeAborted("IncludeAborted"),
		CleanupHelper_WorkflowDefinition("WorkflowCommons.CleanupHelper_WorkflowDefinition");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public CleanupHelper(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected CleanupHelper(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject cleanupHelperMendixObject)
	{
		if (cleanupHelperMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, cleanupHelperMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.cleanupHelperMendixObject = cleanupHelperMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static workflowcommons.proxies.CleanupHelper initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new workflowcommons.proxies.CleanupHelper(context, mendixObject);
	}

	public static workflowcommons.proxies.CleanupHelper load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return workflowcommons.proxies.CleanupHelper.initialize(context, mendixObject);
	}

	/**
	 * @return value of TotalCount
	 */
	public final java.lang.Integer getTotalCount()
	{
		return getTotalCount(getContext());
	}

	/**
	 * @param context
	 * @return value of TotalCount
	 */
	public final java.lang.Integer getTotalCount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.TotalCount.toString());
	}

	/**
	 * Set value of TotalCount
	 * @param totalcount
	 */
	public final void setTotalCount(java.lang.Integer totalcount)
	{
		setTotalCount(getContext(), totalcount);
	}

	/**
	 * Set value of TotalCount
	 * @param context
	 * @param totalcount
	 */
	public final void setTotalCount(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer totalcount)
	{
		getMendixObject().setValue(context, MemberNames.TotalCount.toString(), totalcount);
	}

	/**
	 * @return value of WorkflowName
	 */
	public final java.lang.String getWorkflowName()
	{
		return getWorkflowName(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkflowName
	 */
	public final java.lang.String getWorkflowName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.WorkflowName.toString());
	}

	/**
	 * Set value of WorkflowName
	 * @param workflowname
	 */
	public final void setWorkflowName(java.lang.String workflowname)
	{
		setWorkflowName(getContext(), workflowname);
	}

	/**
	 * Set value of WorkflowName
	 * @param context
	 * @param workflowname
	 */
	public final void setWorkflowName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String workflowname)
	{
		getMendixObject().setValue(context, MemberNames.WorkflowName.toString(), workflowname);
	}

	/**
	 * @return value of StartDateStart
	 */
	public final java.util.Date getStartDateStart()
	{
		return getStartDateStart(getContext());
	}

	/**
	 * @param context
	 * @return value of StartDateStart
	 */
	public final java.util.Date getStartDateStart(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.StartDateStart.toString());
	}

	/**
	 * Set value of StartDateStart
	 * @param startdatestart
	 */
	public final void setStartDateStart(java.util.Date startdatestart)
	{
		setStartDateStart(getContext(), startdatestart);
	}

	/**
	 * Set value of StartDateStart
	 * @param context
	 * @param startdatestart
	 */
	public final void setStartDateStart(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date startdatestart)
	{
		getMendixObject().setValue(context, MemberNames.StartDateStart.toString(), startdatestart);
	}

	/**
	 * @return value of StartDateEnd
	 */
	public final java.util.Date getStartDateEnd()
	{
		return getStartDateEnd(getContext());
	}

	/**
	 * @param context
	 * @return value of StartDateEnd
	 */
	public final java.util.Date getStartDateEnd(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.StartDateEnd.toString());
	}

	/**
	 * Set value of StartDateEnd
	 * @param startdateend
	 */
	public final void setStartDateEnd(java.util.Date startdateend)
	{
		setStartDateEnd(getContext(), startdateend);
	}

	/**
	 * Set value of StartDateEnd
	 * @param context
	 * @param startdateend
	 */
	public final void setStartDateEnd(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date startdateend)
	{
		getMendixObject().setValue(context, MemberNames.StartDateEnd.toString(), startdateend);
	}

	/**
	 * @return value of EndDateStart
	 */
	public final java.util.Date getEndDateStart()
	{
		return getEndDateStart(getContext());
	}

	/**
	 * @param context
	 * @return value of EndDateStart
	 */
	public final java.util.Date getEndDateStart(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.EndDateStart.toString());
	}

	/**
	 * Set value of EndDateStart
	 * @param enddatestart
	 */
	public final void setEndDateStart(java.util.Date enddatestart)
	{
		setEndDateStart(getContext(), enddatestart);
	}

	/**
	 * Set value of EndDateStart
	 * @param context
	 * @param enddatestart
	 */
	public final void setEndDateStart(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date enddatestart)
	{
		getMendixObject().setValue(context, MemberNames.EndDateStart.toString(), enddatestart);
	}

	/**
	 * @return value of EndDateEnd
	 */
	public final java.util.Date getEndDateEnd()
	{
		return getEndDateEnd(getContext());
	}

	/**
	 * @param context
	 * @return value of EndDateEnd
	 */
	public final java.util.Date getEndDateEnd(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.EndDateEnd.toString());
	}

	/**
	 * Set value of EndDateEnd
	 * @param enddateend
	 */
	public final void setEndDateEnd(java.util.Date enddateend)
	{
		setEndDateEnd(getContext(), enddateend);
	}

	/**
	 * Set value of EndDateEnd
	 * @param context
	 * @param enddateend
	 */
	public final void setEndDateEnd(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date enddateend)
	{
		getMendixObject().setValue(context, MemberNames.EndDateEnd.toString(), enddateend);
	}

	/**
	 * @return value of IncludeCompleted
	 */
	public final java.lang.Boolean getIncludeCompleted()
	{
		return getIncludeCompleted(getContext());
	}

	/**
	 * @param context
	 * @return value of IncludeCompleted
	 */
	public final java.lang.Boolean getIncludeCompleted(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IncludeCompleted.toString());
	}

	/**
	 * Set value of IncludeCompleted
	 * @param includecompleted
	 */
	public final void setIncludeCompleted(java.lang.Boolean includecompleted)
	{
		setIncludeCompleted(getContext(), includecompleted);
	}

	/**
	 * Set value of IncludeCompleted
	 * @param context
	 * @param includecompleted
	 */
	public final void setIncludeCompleted(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean includecompleted)
	{
		getMendixObject().setValue(context, MemberNames.IncludeCompleted.toString(), includecompleted);
	}

	/**
	 * @return value of IncludeAborted
	 */
	public final java.lang.Boolean getIncludeAborted()
	{
		return getIncludeAborted(getContext());
	}

	/**
	 * @param context
	 * @return value of IncludeAborted
	 */
	public final java.lang.Boolean getIncludeAborted(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IncludeAborted.toString());
	}

	/**
	 * Set value of IncludeAborted
	 * @param includeaborted
	 */
	public final void setIncludeAborted(java.lang.Boolean includeaborted)
	{
		setIncludeAborted(getContext(), includeaborted);
	}

	/**
	 * Set value of IncludeAborted
	 * @param context
	 * @param includeaborted
	 */
	public final void setIncludeAborted(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean includeaborted)
	{
		getMendixObject().setValue(context, MemberNames.IncludeAborted.toString(), includeaborted);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of CleanupHelper_WorkflowDefinition
	 */
	public final system.proxies.WorkflowDefinition getCleanupHelper_WorkflowDefinition() throws com.mendix.core.CoreException
	{
		return getCleanupHelper_WorkflowDefinition(getContext());
	}

	/**
	 * @param context
	 * @return value of CleanupHelper_WorkflowDefinition
	 * @throws com.mendix.core.CoreException
	 */
	public final system.proxies.WorkflowDefinition getCleanupHelper_WorkflowDefinition(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		system.proxies.WorkflowDefinition result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.CleanupHelper_WorkflowDefinition.toString());
		if (identifier != null) {
			result = system.proxies.WorkflowDefinition.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of CleanupHelper_WorkflowDefinition
	 * @param cleanuphelper_workflowdefinition
	 */
	public final void setCleanupHelper_WorkflowDefinition(system.proxies.WorkflowDefinition cleanuphelper_workflowdefinition)
	{
		setCleanupHelper_WorkflowDefinition(getContext(), cleanuphelper_workflowdefinition);
	}

	/**
	 * Set value of CleanupHelper_WorkflowDefinition
	 * @param context
	 * @param cleanuphelper_workflowdefinition
	 */
	public final void setCleanupHelper_WorkflowDefinition(com.mendix.systemwideinterfaces.core.IContext context, system.proxies.WorkflowDefinition cleanuphelper_workflowdefinition)
	{
		if (cleanuphelper_workflowdefinition == null) {
			getMendixObject().setValue(context, MemberNames.CleanupHelper_WorkflowDefinition.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.CleanupHelper_WorkflowDefinition.toString(), cleanuphelper_workflowdefinition.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return cleanupHelperMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final workflowcommons.proxies.CleanupHelper that = (workflowcommons.proxies.CleanupHelper) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
