// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package workflowcommons.proxies;

public class Configuration
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject configurationMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "WorkflowCommons.Configuration";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		VerifiedAttachmentCommentMigration("VerifiedAttachmentCommentMigration"),
		ShowAttachmentCommentMigration("ShowAttachmentCommentMigration");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Configuration(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Configuration(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject configurationMendixObject)
	{
		if (configurationMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, configurationMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.configurationMendixObject = configurationMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Configuration.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static workflowcommons.proxies.Configuration initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return workflowcommons.proxies.Configuration.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static workflowcommons.proxies.Configuration initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new workflowcommons.proxies.Configuration(context, mendixObject);
	}

	public static workflowcommons.proxies.Configuration load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return workflowcommons.proxies.Configuration.initialize(context, mendixObject);
	}

	public static java.util.List<workflowcommons.proxies.Configuration> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> workflowcommons.proxies.Configuration.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of VerifiedAttachmentCommentMigration
	 */
	public final java.lang.Boolean getVerifiedAttachmentCommentMigration()
	{
		return getVerifiedAttachmentCommentMigration(getContext());
	}

	/**
	 * @param context
	 * @return value of VerifiedAttachmentCommentMigration
	 */
	public final java.lang.Boolean getVerifiedAttachmentCommentMigration(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.VerifiedAttachmentCommentMigration.toString());
	}

	/**
	 * Set value of VerifiedAttachmentCommentMigration
	 * @param verifiedattachmentcommentmigration
	 */
	public final void setVerifiedAttachmentCommentMigration(java.lang.Boolean verifiedattachmentcommentmigration)
	{
		setVerifiedAttachmentCommentMigration(getContext(), verifiedattachmentcommentmigration);
	}

	/**
	 * Set value of VerifiedAttachmentCommentMigration
	 * @param context
	 * @param verifiedattachmentcommentmigration
	 */
	public final void setVerifiedAttachmentCommentMigration(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean verifiedattachmentcommentmigration)
	{
		getMendixObject().setValue(context, MemberNames.VerifiedAttachmentCommentMigration.toString(), verifiedattachmentcommentmigration);
	}

	/**
	 * @return value of ShowAttachmentCommentMigration
	 */
	public final java.lang.Boolean getShowAttachmentCommentMigration()
	{
		return getShowAttachmentCommentMigration(getContext());
	}

	/**
	 * @param context
	 * @return value of ShowAttachmentCommentMigration
	 */
	public final java.lang.Boolean getShowAttachmentCommentMigration(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ShowAttachmentCommentMigration.toString());
	}

	/**
	 * Set value of ShowAttachmentCommentMigration
	 * @param showattachmentcommentmigration
	 */
	public final void setShowAttachmentCommentMigration(java.lang.Boolean showattachmentcommentmigration)
	{
		setShowAttachmentCommentMigration(getContext(), showattachmentcommentmigration);
	}

	/**
	 * Set value of ShowAttachmentCommentMigration
	 * @param context
	 * @param showattachmentcommentmigration
	 */
	public final void setShowAttachmentCommentMigration(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean showattachmentcommentmigration)
	{
		getMendixObject().setValue(context, MemberNames.ShowAttachmentCommentMigration.toString(), showattachmentcommentmigration);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return configurationMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final workflowcommons.proxies.Configuration that = (workflowcommons.proxies.Configuration) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
