// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package workflowcommons.proxies;

public class Configuration implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject configurationMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "WorkflowCommons.Configuration";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		VerifiedAssigneeMigration("VerifiedAssigneeMigration"),
		ShowAssigneeMigration("ShowAssigneeMigration");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Configuration(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Configuration(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject configurationMendixObject)
	{
		if (configurationMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, configurationMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.configurationMendixObject = configurationMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static workflowcommons.proxies.Configuration initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new workflowcommons.proxies.Configuration(context, mendixObject);
	}

	public static workflowcommons.proxies.Configuration load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return workflowcommons.proxies.Configuration.initialize(context, mendixObject);
	}

	public static java.util.List<workflowcommons.proxies.Configuration> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> workflowcommons.proxies.Configuration.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of VerifiedAssigneeMigration
	 */
	public final java.lang.Boolean getVerifiedAssigneeMigration()
	{
		return getVerifiedAssigneeMigration(getContext());
	}

	/**
	 * @param context
	 * @return value of VerifiedAssigneeMigration
	 */
	public final java.lang.Boolean getVerifiedAssigneeMigration(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.VerifiedAssigneeMigration.toString());
	}

	/**
	 * Set value of VerifiedAssigneeMigration
	 * @param verifiedassigneemigration
	 */
	public final void setVerifiedAssigneeMigration(java.lang.Boolean verifiedassigneemigration)
	{
		setVerifiedAssigneeMigration(getContext(), verifiedassigneemigration);
	}

	/**
	 * Set value of VerifiedAssigneeMigration
	 * @param context
	 * @param verifiedassigneemigration
	 */
	public final void setVerifiedAssigneeMigration(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean verifiedassigneemigration)
	{
		getMendixObject().setValue(context, MemberNames.VerifiedAssigneeMigration.toString(), verifiedassigneemigration);
	}

	/**
	 * @return value of ShowAssigneeMigration
	 */
	public final java.lang.Boolean getShowAssigneeMigration()
	{
		return getShowAssigneeMigration(getContext());
	}

	/**
	 * @param context
	 * @return value of ShowAssigneeMigration
	 */
	public final java.lang.Boolean getShowAssigneeMigration(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ShowAssigneeMigration.toString());
	}

	/**
	 * Set value of ShowAssigneeMigration
	 * @param showassigneemigration
	 */
	public final void setShowAssigneeMigration(java.lang.Boolean showassigneemigration)
	{
		setShowAssigneeMigration(getContext(), showassigneemigration);
	}

	/**
	 * Set value of ShowAssigneeMigration
	 * @param context
	 * @param showassigneemigration
	 */
	public final void setShowAssigneeMigration(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean showassigneemigration)
	{
		getMendixObject().setValue(context, MemberNames.ShowAssigneeMigration.toString(), showassigneemigration);
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return configurationMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final workflowcommons.proxies.Configuration that = (workflowcommons.proxies.Configuration) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
