// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package workflowcommons.proxies;

public class DefinitionHelper implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject definitionHelperMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "WorkflowCommons.DefinitionHelper";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		DisplayText("DisplayText"),
		Key("Key"),
		DefinitionHelper_DefinitionHelperParent("WorkflowCommons.DefinitionHelper_DefinitionHelperParent"),
		DefinitionHelper_DashboardContext("WorkflowCommons.DefinitionHelper_DashboardContext"),
		DashboardContext_DefinitionHelperWorkflow("WorkflowCommons.DashboardContext_DefinitionHelperWorkflow"),
		DashboardContext_DefinitionHelperTask("WorkflowCommons.DashboardContext_DefinitionHelperTask");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public DefinitionHelper(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected DefinitionHelper(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject definitionHelperMendixObject)
	{
		if (definitionHelperMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, definitionHelperMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.definitionHelperMendixObject = definitionHelperMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static workflowcommons.proxies.DefinitionHelper initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new workflowcommons.proxies.DefinitionHelper(context, mendixObject);
	}

	public static workflowcommons.proxies.DefinitionHelper load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return workflowcommons.proxies.DefinitionHelper.initialize(context, mendixObject);
	}

	/**
	 * @return value of DisplayText
	 */
	public final java.lang.String getDisplayText()
	{
		return getDisplayText(getContext());
	}

	/**
	 * @param context
	 * @return value of DisplayText
	 */
	public final java.lang.String getDisplayText(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.DisplayText.toString());
	}

	/**
	 * Set value of DisplayText
	 * @param displaytext
	 */
	public final void setDisplayText(java.lang.String displaytext)
	{
		setDisplayText(getContext(), displaytext);
	}

	/**
	 * Set value of DisplayText
	 * @param context
	 * @param displaytext
	 */
	public final void setDisplayText(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String displaytext)
	{
		getMendixObject().setValue(context, MemberNames.DisplayText.toString(), displaytext);
	}

	/**
	 * @return value of Key
	 */
	public final java.lang.String getKey()
	{
		return getKey(getContext());
	}

	/**
	 * @param context
	 * @return value of Key
	 */
	public final java.lang.String getKey(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Key.toString());
	}

	/**
	 * Set value of Key
	 * @param key
	 */
	public final void setKey(java.lang.String key)
	{
		setKey(getContext(), key);
	}

	/**
	 * Set value of Key
	 * @param context
	 * @param key
	 */
	public final void setKey(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String key)
	{
		getMendixObject().setValue(context, MemberNames.Key.toString(), key);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of DefinitionHelper_DefinitionHelperParent
	 */
	public final workflowcommons.proxies.DefinitionHelper getDefinitionHelper_DefinitionHelperParent() throws com.mendix.core.CoreException
	{
		return getDefinitionHelper_DefinitionHelperParent(getContext());
	}

	/**
	 * @param context
	 * @return value of DefinitionHelper_DefinitionHelperParent
	 * @throws com.mendix.core.CoreException
	 */
	public final workflowcommons.proxies.DefinitionHelper getDefinitionHelper_DefinitionHelperParent(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		workflowcommons.proxies.DefinitionHelper result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.DefinitionHelper_DefinitionHelperParent.toString());
		if (identifier != null) {
			result = workflowcommons.proxies.DefinitionHelper.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of DefinitionHelper_DefinitionHelperParent
	 * @param definitionhelper_definitionhelperparent
	 */
	public final void setDefinitionHelper_DefinitionHelperParent(workflowcommons.proxies.DefinitionHelper definitionhelper_definitionhelperparent)
	{
		setDefinitionHelper_DefinitionHelperParent(getContext(), definitionhelper_definitionhelperparent);
	}

	/**
	 * Set value of DefinitionHelper_DefinitionHelperParent
	 * @param context
	 * @param definitionhelper_definitionhelperparent
	 */
	public final void setDefinitionHelper_DefinitionHelperParent(com.mendix.systemwideinterfaces.core.IContext context, workflowcommons.proxies.DefinitionHelper definitionhelper_definitionhelperparent)
	{
		if (definitionhelper_definitionhelperparent == null) {
			getMendixObject().setValue(context, MemberNames.DefinitionHelper_DefinitionHelperParent.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.DefinitionHelper_DefinitionHelperParent.toString(), definitionhelper_definitionhelperparent.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of DefinitionHelper_DashboardContext
	 */
	public final workflowcommons.proxies.DashboardContext getDefinitionHelper_DashboardContext() throws com.mendix.core.CoreException
	{
		return getDefinitionHelper_DashboardContext(getContext());
	}

	/**
	 * @param context
	 * @return value of DefinitionHelper_DashboardContext
	 * @throws com.mendix.core.CoreException
	 */
	public final workflowcommons.proxies.DashboardContext getDefinitionHelper_DashboardContext(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		workflowcommons.proxies.DashboardContext result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.DefinitionHelper_DashboardContext.toString());
		if (identifier != null) {
			result = workflowcommons.proxies.DashboardContext.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of DefinitionHelper_DashboardContext
	 * @param definitionhelper_dashboardcontext
	 */
	public final void setDefinitionHelper_DashboardContext(workflowcommons.proxies.DashboardContext definitionhelper_dashboardcontext)
	{
		setDefinitionHelper_DashboardContext(getContext(), definitionhelper_dashboardcontext);
	}

	/**
	 * Set value of DefinitionHelper_DashboardContext
	 * @param context
	 * @param definitionhelper_dashboardcontext
	 */
	public final void setDefinitionHelper_DashboardContext(com.mendix.systemwideinterfaces.core.IContext context, workflowcommons.proxies.DashboardContext definitionhelper_dashboardcontext)
	{
		if (definitionhelper_dashboardcontext == null) {
			getMendixObject().setValue(context, MemberNames.DefinitionHelper_DashboardContext.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.DefinitionHelper_DashboardContext.toString(), definitionhelper_dashboardcontext.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of DashboardContext_DefinitionHelperWorkflow
	 */
	public final workflowcommons.proxies.DashboardContext getDashboardContext_DefinitionHelperWorkflow() throws com.mendix.core.CoreException
	{
		return getDashboardContext_DefinitionHelperWorkflow(getContext());
	}

	/**
	 * @param context
	 * @return value of DashboardContext_DefinitionHelperWorkflow
	 * @throws com.mendix.core.CoreException
	 */
	public final workflowcommons.proxies.DashboardContext getDashboardContext_DefinitionHelperWorkflow(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		workflowcommons.proxies.DashboardContext result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.DashboardContext_DefinitionHelperWorkflow.toString());
		if (identifier != null) {
			result = workflowcommons.proxies.DashboardContext.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of DashboardContext_DefinitionHelperWorkflow
	 * @param dashboardcontext_definitionhelperworkflow
	 */
	public final void setDashboardContext_DefinitionHelperWorkflow(workflowcommons.proxies.DashboardContext dashboardcontext_definitionhelperworkflow)
	{
		setDashboardContext_DefinitionHelperWorkflow(getContext(), dashboardcontext_definitionhelperworkflow);
	}

	/**
	 * Set value of DashboardContext_DefinitionHelperWorkflow
	 * @param context
	 * @param dashboardcontext_definitionhelperworkflow
	 */
	public final void setDashboardContext_DefinitionHelperWorkflow(com.mendix.systemwideinterfaces.core.IContext context, workflowcommons.proxies.DashboardContext dashboardcontext_definitionhelperworkflow)
	{
		if (dashboardcontext_definitionhelperworkflow == null) {
			getMendixObject().setValue(context, MemberNames.DashboardContext_DefinitionHelperWorkflow.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.DashboardContext_DefinitionHelperWorkflow.toString(), dashboardcontext_definitionhelperworkflow.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of DashboardContext_DefinitionHelperTask
	 */
	public final workflowcommons.proxies.DashboardContext getDashboardContext_DefinitionHelperTask() throws com.mendix.core.CoreException
	{
		return getDashboardContext_DefinitionHelperTask(getContext());
	}

	/**
	 * @param context
	 * @return value of DashboardContext_DefinitionHelperTask
	 * @throws com.mendix.core.CoreException
	 */
	public final workflowcommons.proxies.DashboardContext getDashboardContext_DefinitionHelperTask(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		workflowcommons.proxies.DashboardContext result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.DashboardContext_DefinitionHelperTask.toString());
		if (identifier != null) {
			result = workflowcommons.proxies.DashboardContext.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of DashboardContext_DefinitionHelperTask
	 * @param dashboardcontext_definitionhelpertask
	 */
	public final void setDashboardContext_DefinitionHelperTask(workflowcommons.proxies.DashboardContext dashboardcontext_definitionhelpertask)
	{
		setDashboardContext_DefinitionHelperTask(getContext(), dashboardcontext_definitionhelpertask);
	}

	/**
	 * Set value of DashboardContext_DefinitionHelperTask
	 * @param context
	 * @param dashboardcontext_definitionhelpertask
	 */
	public final void setDashboardContext_DefinitionHelperTask(com.mendix.systemwideinterfaces.core.IContext context, workflowcommons.proxies.DashboardContext dashboardcontext_definitionhelpertask)
	{
		if (dashboardcontext_definitionhelpertask == null) {
			getMendixObject().setValue(context, MemberNames.DashboardContext_DefinitionHelperTask.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.DashboardContext_DefinitionHelperTask.toString(), dashboardcontext_definitionhelpertask.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return definitionHelperMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final workflowcommons.proxies.DefinitionHelper that = (workflowcommons.proxies.DefinitionHelper) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
