// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package workflowcommons.proxies;

public class DefinitionHelper
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject definitionHelperMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "WorkflowCommons.DefinitionHelper";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		DisplayText("DisplayText"),
		Key("Key"),
		DashboardContext_DefinitionHelperTask("WorkflowCommons.DashboardContext_DefinitionHelperTask"),
		DashboardContext_DefinitionHelperWorkflow("WorkflowCommons.DashboardContext_DefinitionHelperWorkflow"),
		DefinitionHelper_DashboardContext("WorkflowCommons.DefinitionHelper_DashboardContext"),
		DefinitionHelper_DefinitionHelperParent("WorkflowCommons.DefinitionHelper_DefinitionHelperParent");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public DefinitionHelper(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "WorkflowCommons.DefinitionHelper"));
	}

	protected DefinitionHelper(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject definitionHelperMendixObject)
	{
		if (definitionHelperMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("WorkflowCommons.DefinitionHelper", definitionHelperMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a WorkflowCommons.DefinitionHelper");

		this.definitionHelperMendixObject = definitionHelperMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'DefinitionHelper.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static workflowcommons.proxies.DefinitionHelper initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return workflowcommons.proxies.DefinitionHelper.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static workflowcommons.proxies.DefinitionHelper initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new workflowcommons.proxies.DefinitionHelper(context, mendixObject);
	}

	public static workflowcommons.proxies.DefinitionHelper load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return workflowcommons.proxies.DefinitionHelper.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of DisplayText
	 */
	public final java.lang.String getDisplayText()
	{
		return getDisplayText(getContext());
	}

	/**
	 * @param context
	 * @return value of DisplayText
	 */
	public final java.lang.String getDisplayText(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.DisplayText.toString());
	}

	/**
	 * Set value of DisplayText
	 * @param displaytext
	 */
	public final void setDisplayText(java.lang.String displaytext)
	{
		setDisplayText(getContext(), displaytext);
	}

	/**
	 * Set value of DisplayText
	 * @param context
	 * @param displaytext
	 */
	public final void setDisplayText(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String displaytext)
	{
		getMendixObject().setValue(context, MemberNames.DisplayText.toString(), displaytext);
	}

	/**
	 * @return value of Key
	 */
	public final java.lang.String getKey()
	{
		return getKey(getContext());
	}

	/**
	 * @param context
	 * @return value of Key
	 */
	public final java.lang.String getKey(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Key.toString());
	}

	/**
	 * Set value of Key
	 * @param key
	 */
	public final void setKey(java.lang.String key)
	{
		setKey(getContext(), key);
	}

	/**
	 * Set value of Key
	 * @param context
	 * @param key
	 */
	public final void setKey(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String key)
	{
		getMendixObject().setValue(context, MemberNames.Key.toString(), key);
	}

	/**
	 * @return value of DashboardContext_DefinitionHelperTask
	 */
	public final workflowcommons.proxies.DashboardContext getDashboardContext_DefinitionHelperTask() throws com.mendix.core.CoreException
	{
		return getDashboardContext_DefinitionHelperTask(getContext());
	}

	/**
	 * @param context
	 * @return value of DashboardContext_DefinitionHelperTask
	 */
	public final workflowcommons.proxies.DashboardContext getDashboardContext_DefinitionHelperTask(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		workflowcommons.proxies.DashboardContext result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.DashboardContext_DefinitionHelperTask.toString());
		if (identifier != null)
			result = workflowcommons.proxies.DashboardContext.load(context, identifier);
		return result;
	}

	/**
	 * Set value of DashboardContext_DefinitionHelperTask
	 * @param dashboardcontext_definitionhelpertask
	 */
	public final void setDashboardContext_DefinitionHelperTask(workflowcommons.proxies.DashboardContext dashboardcontext_definitionhelpertask)
	{
		setDashboardContext_DefinitionHelperTask(getContext(), dashboardcontext_definitionhelpertask);
	}

	/**
	 * Set value of DashboardContext_DefinitionHelperTask
	 * @param context
	 * @param dashboardcontext_definitionhelpertask
	 */
	public final void setDashboardContext_DefinitionHelperTask(com.mendix.systemwideinterfaces.core.IContext context, workflowcommons.proxies.DashboardContext dashboardcontext_definitionhelpertask)
	{
		if (dashboardcontext_definitionhelpertask == null)
			getMendixObject().setValue(context, MemberNames.DashboardContext_DefinitionHelperTask.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.DashboardContext_DefinitionHelperTask.toString(), dashboardcontext_definitionhelpertask.getMendixObject().getId());
	}

	/**
	 * @return value of DashboardContext_DefinitionHelperWorkflow
	 */
	public final workflowcommons.proxies.DashboardContext getDashboardContext_DefinitionHelperWorkflow() throws com.mendix.core.CoreException
	{
		return getDashboardContext_DefinitionHelperWorkflow(getContext());
	}

	/**
	 * @param context
	 * @return value of DashboardContext_DefinitionHelperWorkflow
	 */
	public final workflowcommons.proxies.DashboardContext getDashboardContext_DefinitionHelperWorkflow(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		workflowcommons.proxies.DashboardContext result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.DashboardContext_DefinitionHelperWorkflow.toString());
		if (identifier != null)
			result = workflowcommons.proxies.DashboardContext.load(context, identifier);
		return result;
	}

	/**
	 * Set value of DashboardContext_DefinitionHelperWorkflow
	 * @param dashboardcontext_definitionhelperworkflow
	 */
	public final void setDashboardContext_DefinitionHelperWorkflow(workflowcommons.proxies.DashboardContext dashboardcontext_definitionhelperworkflow)
	{
		setDashboardContext_DefinitionHelperWorkflow(getContext(), dashboardcontext_definitionhelperworkflow);
	}

	/**
	 * Set value of DashboardContext_DefinitionHelperWorkflow
	 * @param context
	 * @param dashboardcontext_definitionhelperworkflow
	 */
	public final void setDashboardContext_DefinitionHelperWorkflow(com.mendix.systemwideinterfaces.core.IContext context, workflowcommons.proxies.DashboardContext dashboardcontext_definitionhelperworkflow)
	{
		if (dashboardcontext_definitionhelperworkflow == null)
			getMendixObject().setValue(context, MemberNames.DashboardContext_DefinitionHelperWorkflow.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.DashboardContext_DefinitionHelperWorkflow.toString(), dashboardcontext_definitionhelperworkflow.getMendixObject().getId());
	}

	/**
	 * @return value of DefinitionHelper_DashboardContext
	 */
	public final workflowcommons.proxies.DashboardContext getDefinitionHelper_DashboardContext() throws com.mendix.core.CoreException
	{
		return getDefinitionHelper_DashboardContext(getContext());
	}

	/**
	 * @param context
	 * @return value of DefinitionHelper_DashboardContext
	 */
	public final workflowcommons.proxies.DashboardContext getDefinitionHelper_DashboardContext(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		workflowcommons.proxies.DashboardContext result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.DefinitionHelper_DashboardContext.toString());
		if (identifier != null)
			result = workflowcommons.proxies.DashboardContext.load(context, identifier);
		return result;
	}

	/**
	 * Set value of DefinitionHelper_DashboardContext
	 * @param definitionhelper_dashboardcontext
	 */
	public final void setDefinitionHelper_DashboardContext(workflowcommons.proxies.DashboardContext definitionhelper_dashboardcontext)
	{
		setDefinitionHelper_DashboardContext(getContext(), definitionhelper_dashboardcontext);
	}

	/**
	 * Set value of DefinitionHelper_DashboardContext
	 * @param context
	 * @param definitionhelper_dashboardcontext
	 */
	public final void setDefinitionHelper_DashboardContext(com.mendix.systemwideinterfaces.core.IContext context, workflowcommons.proxies.DashboardContext definitionhelper_dashboardcontext)
	{
		if (definitionhelper_dashboardcontext == null)
			getMendixObject().setValue(context, MemberNames.DefinitionHelper_DashboardContext.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.DefinitionHelper_DashboardContext.toString(), definitionhelper_dashboardcontext.getMendixObject().getId());
	}

	/**
	 * @return value of DefinitionHelper_DefinitionHelperParent
	 */
	public final workflowcommons.proxies.DefinitionHelper getDefinitionHelper_DefinitionHelperParent() throws com.mendix.core.CoreException
	{
		return getDefinitionHelper_DefinitionHelperParent(getContext());
	}

	/**
	 * @param context
	 * @return value of DefinitionHelper_DefinitionHelperParent
	 */
	public final workflowcommons.proxies.DefinitionHelper getDefinitionHelper_DefinitionHelperParent(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		workflowcommons.proxies.DefinitionHelper result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.DefinitionHelper_DefinitionHelperParent.toString());
		if (identifier != null)
			result = workflowcommons.proxies.DefinitionHelper.load(context, identifier);
		return result;
	}

	/**
	 * Set value of DefinitionHelper_DefinitionHelperParent
	 * @param definitionhelper_definitionhelperparent
	 */
	public final void setDefinitionHelper_DefinitionHelperParent(workflowcommons.proxies.DefinitionHelper definitionhelper_definitionhelperparent)
	{
		setDefinitionHelper_DefinitionHelperParent(getContext(), definitionhelper_definitionhelperparent);
	}

	/**
	 * Set value of DefinitionHelper_DefinitionHelperParent
	 * @param context
	 * @param definitionhelper_definitionhelperparent
	 */
	public final void setDefinitionHelper_DefinitionHelperParent(com.mendix.systemwideinterfaces.core.IContext context, workflowcommons.proxies.DefinitionHelper definitionhelper_definitionhelperparent)
	{
		if (definitionhelper_definitionhelperparent == null)
			getMendixObject().setValue(context, MemberNames.DefinitionHelper_DefinitionHelperParent.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.DefinitionHelper_DefinitionHelperParent.toString(), definitionhelper_definitionhelperparent.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return definitionHelperMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final workflowcommons.proxies.DefinitionHelper that = (workflowcommons.proxies.DefinitionHelper) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "WorkflowCommons.DefinitionHelper";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
