// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package workflowcommons.proxies;

public class TaskSeries implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject taskSeriesMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "WorkflowCommons.TaskSeries";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		DateDisplay("DateDisplay"),
		Date("Date"),
		NumberofTasksCompletedOnTime("NumberofTasksCompletedOnTime"),
		AverageTaskHandlingTime("AverageTaskHandlingTime"),
		TasksHandledOnTime("TasksHandledOnTime"),
		NumberOfTasksCompletedOverdue("NumberOfTasksCompletedOverdue"),
		TaskSeries_DashboardContext("WorkflowCommons.TaskSeries_DashboardContext");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public TaskSeries(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected TaskSeries(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject taskSeriesMendixObject)
	{
		if (taskSeriesMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, taskSeriesMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.taskSeriesMendixObject = taskSeriesMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static workflowcommons.proxies.TaskSeries initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new workflowcommons.proxies.TaskSeries(context, mendixObject);
	}

	public static workflowcommons.proxies.TaskSeries load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return workflowcommons.proxies.TaskSeries.initialize(context, mendixObject);
	}

	/**
	 * @return value of DateDisplay
	 */
	public final java.lang.String getDateDisplay()
	{
		return getDateDisplay(getContext());
	}

	/**
	 * @param context
	 * @return value of DateDisplay
	 */
	public final java.lang.String getDateDisplay(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.DateDisplay.toString());
	}

	/**
	 * Set value of DateDisplay
	 * @param datedisplay
	 */
	public final void setDateDisplay(java.lang.String datedisplay)
	{
		setDateDisplay(getContext(), datedisplay);
	}

	/**
	 * Set value of DateDisplay
	 * @param context
	 * @param datedisplay
	 */
	public final void setDateDisplay(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String datedisplay)
	{
		getMendixObject().setValue(context, MemberNames.DateDisplay.toString(), datedisplay);
	}

	/**
	 * @return value of Date
	 */
	public final java.util.Date getDate()
	{
		return getDate(getContext());
	}

	/**
	 * @param context
	 * @return value of Date
	 */
	public final java.util.Date getDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.Date.toString());
	}

	/**
	 * Set value of Date
	 * @param date
	 */
	public final void setDate(java.util.Date date)
	{
		setDate(getContext(), date);
	}

	/**
	 * Set value of Date
	 * @param context
	 * @param date
	 */
	public final void setDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date date)
	{
		getMendixObject().setValue(context, MemberNames.Date.toString(), date);
	}

	/**
	 * @return value of NumberofTasksCompletedOnTime
	 */
	public final java.lang.Integer getNumberofTasksCompletedOnTime()
	{
		return getNumberofTasksCompletedOnTime(getContext());
	}

	/**
	 * @param context
	 * @return value of NumberofTasksCompletedOnTime
	 */
	public final java.lang.Integer getNumberofTasksCompletedOnTime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.NumberofTasksCompletedOnTime.toString());
	}

	/**
	 * Set value of NumberofTasksCompletedOnTime
	 * @param numberoftaskscompletedontime
	 */
	public final void setNumberofTasksCompletedOnTime(java.lang.Integer numberoftaskscompletedontime)
	{
		setNumberofTasksCompletedOnTime(getContext(), numberoftaskscompletedontime);
	}

	/**
	 * Set value of NumberofTasksCompletedOnTime
	 * @param context
	 * @param numberoftaskscompletedontime
	 */
	public final void setNumberofTasksCompletedOnTime(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer numberoftaskscompletedontime)
	{
		getMendixObject().setValue(context, MemberNames.NumberofTasksCompletedOnTime.toString(), numberoftaskscompletedontime);
	}

	/**
	 * @return value of AverageTaskHandlingTime
	 */
	public final java.math.BigDecimal getAverageTaskHandlingTime()
	{
		return getAverageTaskHandlingTime(getContext());
	}

	/**
	 * @param context
	 * @return value of AverageTaskHandlingTime
	 */
	public final java.math.BigDecimal getAverageTaskHandlingTime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.AverageTaskHandlingTime.toString());
	}

	/**
	 * Set value of AverageTaskHandlingTime
	 * @param averagetaskhandlingtime
	 */
	public final void setAverageTaskHandlingTime(java.math.BigDecimal averagetaskhandlingtime)
	{
		setAverageTaskHandlingTime(getContext(), averagetaskhandlingtime);
	}

	/**
	 * Set value of AverageTaskHandlingTime
	 * @param context
	 * @param averagetaskhandlingtime
	 */
	public final void setAverageTaskHandlingTime(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal averagetaskhandlingtime)
	{
		getMendixObject().setValue(context, MemberNames.AverageTaskHandlingTime.toString(), averagetaskhandlingtime);
	}

	/**
	 * @return value of TasksHandledOnTime
	 */
	public final java.math.BigDecimal getTasksHandledOnTime()
	{
		return getTasksHandledOnTime(getContext());
	}

	/**
	 * @param context
	 * @return value of TasksHandledOnTime
	 */
	public final java.math.BigDecimal getTasksHandledOnTime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.TasksHandledOnTime.toString());
	}

	/**
	 * Set value of TasksHandledOnTime
	 * @param taskshandledontime
	 */
	public final void setTasksHandledOnTime(java.math.BigDecimal taskshandledontime)
	{
		setTasksHandledOnTime(getContext(), taskshandledontime);
	}

	/**
	 * Set value of TasksHandledOnTime
	 * @param context
	 * @param taskshandledontime
	 */
	public final void setTasksHandledOnTime(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal taskshandledontime)
	{
		getMendixObject().setValue(context, MemberNames.TasksHandledOnTime.toString(), taskshandledontime);
	}

	/**
	 * @return value of NumberOfTasksCompletedOverdue
	 */
	public final java.lang.Integer getNumberOfTasksCompletedOverdue()
	{
		return getNumberOfTasksCompletedOverdue(getContext());
	}

	/**
	 * @param context
	 * @return value of NumberOfTasksCompletedOverdue
	 */
	public final java.lang.Integer getNumberOfTasksCompletedOverdue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.NumberOfTasksCompletedOverdue.toString());
	}

	/**
	 * Set value of NumberOfTasksCompletedOverdue
	 * @param numberoftaskscompletedoverdue
	 */
	public final void setNumberOfTasksCompletedOverdue(java.lang.Integer numberoftaskscompletedoverdue)
	{
		setNumberOfTasksCompletedOverdue(getContext(), numberoftaskscompletedoverdue);
	}

	/**
	 * Set value of NumberOfTasksCompletedOverdue
	 * @param context
	 * @param numberoftaskscompletedoverdue
	 */
	public final void setNumberOfTasksCompletedOverdue(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer numberoftaskscompletedoverdue)
	{
		getMendixObject().setValue(context, MemberNames.NumberOfTasksCompletedOverdue.toString(), numberoftaskscompletedoverdue);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of TaskSeries_DashboardContext
	 */
	public final workflowcommons.proxies.DashboardContext getTaskSeries_DashboardContext() throws com.mendix.core.CoreException
	{
		return getTaskSeries_DashboardContext(getContext());
	}

	/**
	 * @param context
	 * @return value of TaskSeries_DashboardContext
	 * @throws com.mendix.core.CoreException
	 */
	public final workflowcommons.proxies.DashboardContext getTaskSeries_DashboardContext(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		workflowcommons.proxies.DashboardContext result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.TaskSeries_DashboardContext.toString());
		if (identifier != null) {
			result = workflowcommons.proxies.DashboardContext.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of TaskSeries_DashboardContext
	 * @param taskseries_dashboardcontext
	 */
	public final void setTaskSeries_DashboardContext(workflowcommons.proxies.DashboardContext taskseries_dashboardcontext)
	{
		setTaskSeries_DashboardContext(getContext(), taskseries_dashboardcontext);
	}

	/**
	 * Set value of TaskSeries_DashboardContext
	 * @param context
	 * @param taskseries_dashboardcontext
	 */
	public final void setTaskSeries_DashboardContext(com.mendix.systemwideinterfaces.core.IContext context, workflowcommons.proxies.DashboardContext taskseries_dashboardcontext)
	{
		if (taskseries_dashboardcontext == null) {
			getMendixObject().setValue(context, MemberNames.TaskSeries_DashboardContext.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.TaskSeries_DashboardContext.toString(), taskseries_dashboardcontext.getMendixObject().getId());
		}
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return taskSeriesMendixObject;
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final workflowcommons.proxies.TaskSeries that = (workflowcommons.proxies.TaskSeries) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
