// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package workflowcommons.proxies;

public class TimelineViewer implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject timelineViewerMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "WorkflowCommons.TimelineViewer";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		TimelineViewer_Workflow("WorkflowCommons.TimelineViewer_Workflow");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public TimelineViewer(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected TimelineViewer(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject timelineViewerMendixObject)
	{
		if (timelineViewerMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, timelineViewerMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.timelineViewerMendixObject = timelineViewerMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static workflowcommons.proxies.TimelineViewer initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new workflowcommons.proxies.TimelineViewer(context, mendixObject);
	}

	public static workflowcommons.proxies.TimelineViewer load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return workflowcommons.proxies.TimelineViewer.initialize(context, mendixObject);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of TimelineViewer_Workflow
	 */
	public final system.proxies.Workflow getTimelineViewer_Workflow() throws com.mendix.core.CoreException
	{
		return getTimelineViewer_Workflow(getContext());
	}

	/**
	 * @param context
	 * @return value of TimelineViewer_Workflow
	 * @throws com.mendix.core.CoreException
	 */
	public final system.proxies.Workflow getTimelineViewer_Workflow(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		system.proxies.Workflow result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.TimelineViewer_Workflow.toString());
		if (identifier != null) {
			result = system.proxies.Workflow.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of TimelineViewer_Workflow
	 * @param timelineviewer_workflow
	 */
	public final void setTimelineViewer_Workflow(system.proxies.Workflow timelineviewer_workflow)
	{
		setTimelineViewer_Workflow(getContext(), timelineviewer_workflow);
	}

	/**
	 * Set value of TimelineViewer_Workflow
	 * @param context
	 * @param timelineviewer_workflow
	 */
	public final void setTimelineViewer_Workflow(com.mendix.systemwideinterfaces.core.IContext context, system.proxies.Workflow timelineviewer_workflow)
	{
		if (timelineviewer_workflow == null) {
			getMendixObject().setValue(context, MemberNames.TimelineViewer_Workflow.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.TimelineViewer_Workflow.toString(), timelineviewer_workflow.getMendixObject().getId());
		}
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return timelineViewerMendixObject;
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final workflowcommons.proxies.TimelineViewer that = (workflowcommons.proxies.TimelineViewer) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
