// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package workflowcommons.proxies;

public class UserTaskTimeLine implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject userTaskTimeLineMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "WorkflowCommons.UserTaskTimeLine";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		TaskName("TaskName"),
		CompletedOn("CompletedOn"),
		CompletionType("CompletionType"),
		OutcomeCount("OutcomeCount"),
		Outcome("Outcome"),
		State("State"),
		StartedOn("StartedOn"),
		Assignees("Assignees");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public UserTaskTimeLine(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected UserTaskTimeLine(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject userTaskTimeLineMendixObject)
	{
		if (userTaskTimeLineMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, userTaskTimeLineMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.userTaskTimeLineMendixObject = userTaskTimeLineMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static workflowcommons.proxies.UserTaskTimeLine initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new workflowcommons.proxies.UserTaskTimeLine(context, mendixObject);
	}

	public static workflowcommons.proxies.UserTaskTimeLine load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return workflowcommons.proxies.UserTaskTimeLine.initialize(context, mendixObject);
	}

	/**
	 * @return value of TaskName
	 */
	public final java.lang.String getTaskName()
	{
		return getTaskName(getContext());
	}

	/**
	 * @param context
	 * @return value of TaskName
	 */
	public final java.lang.String getTaskName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.TaskName.toString());
	}

	/**
	 * Set value of TaskName
	 * @param taskname
	 */
	public final void setTaskName(java.lang.String taskname)
	{
		setTaskName(getContext(), taskname);
	}

	/**
	 * Set value of TaskName
	 * @param context
	 * @param taskname
	 */
	public final void setTaskName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String taskname)
	{
		getMendixObject().setValue(context, MemberNames.TaskName.toString(), taskname);
	}

	/**
	 * @return value of CompletedOn
	 */
	public final java.util.Date getCompletedOn()
	{
		return getCompletedOn(getContext());
	}

	/**
	 * @param context
	 * @return value of CompletedOn
	 */
	public final java.util.Date getCompletedOn(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.CompletedOn.toString());
	}

	/**
	 * Set value of CompletedOn
	 * @param completedon
	 */
	public final void setCompletedOn(java.util.Date completedon)
	{
		setCompletedOn(getContext(), completedon);
	}

	/**
	 * Set value of CompletedOn
	 * @param context
	 * @param completedon
	 */
	public final void setCompletedOn(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date completedon)
	{
		getMendixObject().setValue(context, MemberNames.CompletedOn.toString(), completedon);
	}

	/**
	 * Get value of CompletionType
	 * @param completiontype
	 */
	public final system.proxies.WorkflowUserTaskCompletionType getCompletionType()
	{
		return getCompletionType(getContext());
	}

	/**
	 * @param context
	 * @return value of CompletionType
	 */
	public final system.proxies.WorkflowUserTaskCompletionType getCompletionType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.CompletionType.toString());
		if (obj == null) {
			return null;
		}
		return system.proxies.WorkflowUserTaskCompletionType.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of CompletionType
	 * @param completiontype
	 */
	public final void setCompletionType(system.proxies.WorkflowUserTaskCompletionType completiontype)
	{
		setCompletionType(getContext(), completiontype);
	}

	/**
	 * Set value of CompletionType
	 * @param context
	 * @param completiontype
	 */
	public final void setCompletionType(com.mendix.systemwideinterfaces.core.IContext context, system.proxies.WorkflowUserTaskCompletionType completiontype)
	{
		if (completiontype != null) {
			getMendixObject().setValue(context, MemberNames.CompletionType.toString(), completiontype.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.CompletionType.toString(), null);
		}
	}

	/**
	 * @return value of OutcomeCount
	 */
	public final java.lang.Integer getOutcomeCount()
	{
		return getOutcomeCount(getContext());
	}

	/**
	 * @param context
	 * @return value of OutcomeCount
	 */
	public final java.lang.Integer getOutcomeCount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.OutcomeCount.toString());
	}

	/**
	 * Set value of OutcomeCount
	 * @param outcomecount
	 */
	public final void setOutcomeCount(java.lang.Integer outcomecount)
	{
		setOutcomeCount(getContext(), outcomecount);
	}

	/**
	 * Set value of OutcomeCount
	 * @param context
	 * @param outcomecount
	 */
	public final void setOutcomeCount(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer outcomecount)
	{
		getMendixObject().setValue(context, MemberNames.OutcomeCount.toString(), outcomecount);
	}

	/**
	 * @return value of Outcome
	 */
	public final java.lang.String getOutcome()
	{
		return getOutcome(getContext());
	}

	/**
	 * @param context
	 * @return value of Outcome
	 */
	public final java.lang.String getOutcome(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Outcome.toString());
	}

	/**
	 * Set value of Outcome
	 * @param outcome
	 */
	public final void setOutcome(java.lang.String outcome)
	{
		setOutcome(getContext(), outcome);
	}

	/**
	 * Set value of Outcome
	 * @param context
	 * @param outcome
	 */
	public final void setOutcome(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String outcome)
	{
		getMendixObject().setValue(context, MemberNames.Outcome.toString(), outcome);
	}

	/**
	 * Get value of State
	 * @param state
	 */
	public final system.proxies.WorkflowUserTaskState getState()
	{
		return getState(getContext());
	}

	/**
	 * @param context
	 * @return value of State
	 */
	public final system.proxies.WorkflowUserTaskState getState(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.State.toString());
		if (obj == null) {
			return null;
		}
		return system.proxies.WorkflowUserTaskState.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of State
	 * @param state
	 */
	public final void setState(system.proxies.WorkflowUserTaskState state)
	{
		setState(getContext(), state);
	}

	/**
	 * Set value of State
	 * @param context
	 * @param state
	 */
	public final void setState(com.mendix.systemwideinterfaces.core.IContext context, system.proxies.WorkflowUserTaskState state)
	{
		if (state != null) {
			getMendixObject().setValue(context, MemberNames.State.toString(), state.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.State.toString(), null);
		}
	}

	/**
	 * @return value of StartedOn
	 */
	public final java.util.Date getStartedOn()
	{
		return getStartedOn(getContext());
	}

	/**
	 * @param context
	 * @return value of StartedOn
	 */
	public final java.util.Date getStartedOn(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.StartedOn.toString());
	}

	/**
	 * Set value of StartedOn
	 * @param startedon
	 */
	public final void setStartedOn(java.util.Date startedon)
	{
		setStartedOn(getContext(), startedon);
	}

	/**
	 * Set value of StartedOn
	 * @param context
	 * @param startedon
	 */
	public final void setStartedOn(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date startedon)
	{
		getMendixObject().setValue(context, MemberNames.StartedOn.toString(), startedon);
	}

	/**
	 * @return value of Assignees
	 */
	public final java.lang.String getAssignees()
	{
		return getAssignees(getContext());
	}

	/**
	 * @param context
	 * @return value of Assignees
	 */
	public final java.lang.String getAssignees(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Assignees.toString());
	}

	/**
	 * Set value of Assignees
	 * @param assignees
	 */
	public final void setAssignees(java.lang.String assignees)
	{
		setAssignees(getContext(), assignees);
	}

	/**
	 * Set value of Assignees
	 * @param context
	 * @param assignees
	 */
	public final void setAssignees(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String assignees)
	{
		getMendixObject().setValue(context, MemberNames.Assignees.toString(), assignees);
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return userTaskTimeLineMendixObject;
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final workflowcommons.proxies.UserTaskTimeLine that = (workflowcommons.proxies.UserTaskTimeLine) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
