// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package workflowcommons.proxies;

public class UserTaskOutcomeView implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject userTaskOutcomeViewMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "WorkflowCommons.UserTaskOutcomeView";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Outcome("Outcome"),
		Time("Time"),
		UserTaskOutcomeView_UserTaskView("WorkflowCommons.UserTaskOutcomeView_UserTaskView"),
		UserTaskOutcomeView_User("WorkflowCommons.UserTaskOutcomeView_User"),
		UserTaskOutcomeView_WorkflowUserTaskOutcome("WorkflowCommons.UserTaskOutcomeView_WorkflowUserTaskOutcome");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public UserTaskOutcomeView(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected UserTaskOutcomeView(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject userTaskOutcomeViewMendixObject)
	{
		if (userTaskOutcomeViewMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, userTaskOutcomeViewMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.userTaskOutcomeViewMendixObject = userTaskOutcomeViewMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static workflowcommons.proxies.UserTaskOutcomeView initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new workflowcommons.proxies.UserTaskOutcomeView(context, mendixObject);
	}

	public static workflowcommons.proxies.UserTaskOutcomeView load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return workflowcommons.proxies.UserTaskOutcomeView.initialize(context, mendixObject);
	}

	public static java.util.List<workflowcommons.proxies.UserTaskOutcomeView> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> workflowcommons.proxies.UserTaskOutcomeView.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of Outcome
	 */
	public final java.lang.String getOutcome()
	{
		return getOutcome(getContext());
	}

	/**
	 * @param context
	 * @return value of Outcome
	 */
	public final java.lang.String getOutcome(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Outcome.toString());
	}

	/**
	 * Set value of Outcome
	 * @param outcome
	 */
	public final void setOutcome(java.lang.String outcome)
	{
		setOutcome(getContext(), outcome);
	}

	/**
	 * Set value of Outcome
	 * @param context
	 * @param outcome
	 */
	public final void setOutcome(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String outcome)
	{
		getMendixObject().setValue(context, MemberNames.Outcome.toString(), outcome);
	}

	/**
	 * @return value of Time
	 */
	public final java.util.Date getTime()
	{
		return getTime(getContext());
	}

	/**
	 * @param context
	 * @return value of Time
	 */
	public final java.util.Date getTime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.Time.toString());
	}

	/**
	 * Set value of Time
	 * @param time
	 */
	public final void setTime(java.util.Date time)
	{
		setTime(getContext(), time);
	}

	/**
	 * Set value of Time
	 * @param context
	 * @param time
	 */
	public final void setTime(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date time)
	{
		getMendixObject().setValue(context, MemberNames.Time.toString(), time);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of UserTaskOutcomeView_UserTaskView
	 */
	public final workflowcommons.proxies.UserTaskView getUserTaskOutcomeView_UserTaskView() throws com.mendix.core.CoreException
	{
		return getUserTaskOutcomeView_UserTaskView(getContext());
	}

	/**
	 * @param context
	 * @return value of UserTaskOutcomeView_UserTaskView
	 * @throws com.mendix.core.CoreException
	 */
	public final workflowcommons.proxies.UserTaskView getUserTaskOutcomeView_UserTaskView(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		workflowcommons.proxies.UserTaskView result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.UserTaskOutcomeView_UserTaskView.toString());
		if (identifier != null) {
			result = workflowcommons.proxies.UserTaskView.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of UserTaskOutcomeView_UserTaskView
	 * @param usertaskoutcomeview_usertaskview
	 */
	public final void setUserTaskOutcomeView_UserTaskView(workflowcommons.proxies.UserTaskView usertaskoutcomeview_usertaskview)
	{
		setUserTaskOutcomeView_UserTaskView(getContext(), usertaskoutcomeview_usertaskview);
	}

	/**
	 * Set value of UserTaskOutcomeView_UserTaskView
	 * @param context
	 * @param usertaskoutcomeview_usertaskview
	 */
	public final void setUserTaskOutcomeView_UserTaskView(com.mendix.systemwideinterfaces.core.IContext context, workflowcommons.proxies.UserTaskView usertaskoutcomeview_usertaskview)
	{
		if (usertaskoutcomeview_usertaskview == null) {
			getMendixObject().setValue(context, MemberNames.UserTaskOutcomeView_UserTaskView.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.UserTaskOutcomeView_UserTaskView.toString(), usertaskoutcomeview_usertaskview.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of UserTaskOutcomeView_User
	 */
	public final system.proxies.User getUserTaskOutcomeView_User() throws com.mendix.core.CoreException
	{
		return getUserTaskOutcomeView_User(getContext());
	}

	/**
	 * @param context
	 * @return value of UserTaskOutcomeView_User
	 * @throws com.mendix.core.CoreException
	 */
	public final system.proxies.User getUserTaskOutcomeView_User(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		system.proxies.User result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.UserTaskOutcomeView_User.toString());
		if (identifier != null) {
			result = system.proxies.User.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of UserTaskOutcomeView_User
	 * @param usertaskoutcomeview_user
	 */
	public final void setUserTaskOutcomeView_User(system.proxies.User usertaskoutcomeview_user)
	{
		setUserTaskOutcomeView_User(getContext(), usertaskoutcomeview_user);
	}

	/**
	 * Set value of UserTaskOutcomeView_User
	 * @param context
	 * @param usertaskoutcomeview_user
	 */
	public final void setUserTaskOutcomeView_User(com.mendix.systemwideinterfaces.core.IContext context, system.proxies.User usertaskoutcomeview_user)
	{
		if (usertaskoutcomeview_user == null) {
			getMendixObject().setValue(context, MemberNames.UserTaskOutcomeView_User.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.UserTaskOutcomeView_User.toString(), usertaskoutcomeview_user.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of UserTaskOutcomeView_WorkflowUserTaskOutcome
	 */
	public final system.proxies.WorkflowUserTaskOutcome getUserTaskOutcomeView_WorkflowUserTaskOutcome() throws com.mendix.core.CoreException
	{
		return getUserTaskOutcomeView_WorkflowUserTaskOutcome(getContext());
	}

	/**
	 * @param context
	 * @return value of UserTaskOutcomeView_WorkflowUserTaskOutcome
	 * @throws com.mendix.core.CoreException
	 */
	public final system.proxies.WorkflowUserTaskOutcome getUserTaskOutcomeView_WorkflowUserTaskOutcome(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		system.proxies.WorkflowUserTaskOutcome result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.UserTaskOutcomeView_WorkflowUserTaskOutcome.toString());
		if (identifier != null) {
			result = system.proxies.WorkflowUserTaskOutcome.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of UserTaskOutcomeView_WorkflowUserTaskOutcome
	 * @param usertaskoutcomeview_workflowusertaskoutcome
	 */
	public final void setUserTaskOutcomeView_WorkflowUserTaskOutcome(system.proxies.WorkflowUserTaskOutcome usertaskoutcomeview_workflowusertaskoutcome)
	{
		setUserTaskOutcomeView_WorkflowUserTaskOutcome(getContext(), usertaskoutcomeview_workflowusertaskoutcome);
	}

	/**
	 * Set value of UserTaskOutcomeView_WorkflowUserTaskOutcome
	 * @param context
	 * @param usertaskoutcomeview_workflowusertaskoutcome
	 */
	public final void setUserTaskOutcomeView_WorkflowUserTaskOutcome(com.mendix.systemwideinterfaces.core.IContext context, system.proxies.WorkflowUserTaskOutcome usertaskoutcomeview_workflowusertaskoutcome)
	{
		if (usertaskoutcomeview_workflowusertaskoutcome == null) {
			getMendixObject().setValue(context, MemberNames.UserTaskOutcomeView_WorkflowUserTaskOutcome.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.UserTaskOutcomeView_WorkflowUserTaskOutcome.toString(), usertaskoutcomeview_workflowusertaskoutcome.getMendixObject().getId());
		}
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return userTaskOutcomeViewMendixObject;
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final workflowcommons.proxies.UserTaskOutcomeView that = (workflowcommons.proxies.UserTaskOutcomeView) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
