// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package workflowcommons.proxies;

public class UserTaskView implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject userTaskViewMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "WorkflowCommons.UserTaskView";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		Description("Description"),
		StartTime("StartTime"),
		EndTime("EndTime"),
		DueDate("DueDate"),
		Outcome("Outcome"),
		CompletionType("CompletionType"),
		State("State"),
		UserTaskView_WorkflowView("WorkflowCommons.UserTaskView_WorkflowView"),
		UserTaskView_WorkflowUserTask("WorkflowCommons.UserTaskView_WorkflowUserTask"),
		UserTaskView_WorkflowUserTaskDefinition("WorkflowCommons.UserTaskView_WorkflowUserTaskDefinition"),
		UserTaskView_Assignees("WorkflowCommons.UserTaskView_Assignees"),
		UserTaskView_TargetUsers("WorkflowCommons.UserTaskView_TargetUsers"),
		UserTaskView_Assignee("WorkflowCommons.UserTaskView_Assignee");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public UserTaskView(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected UserTaskView(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject userTaskViewMendixObject)
	{
		if (userTaskViewMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, userTaskViewMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.userTaskViewMendixObject = userTaskViewMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static workflowcommons.proxies.UserTaskView initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new workflowcommons.proxies.UserTaskView(context, mendixObject);
	}

	public static workflowcommons.proxies.UserTaskView load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return workflowcommons.proxies.UserTaskView.initialize(context, mendixObject);
	}

	public static java.util.List<workflowcommons.proxies.UserTaskView> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> workflowcommons.proxies.UserTaskView.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of Description
	 */
	public final java.lang.String getDescription()
	{
		return getDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of Description
	 */
	public final java.lang.String getDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Description.toString());
	}

	/**
	 * Set value of Description
	 * @param description
	 */
	public final void setDescription(java.lang.String description)
	{
		setDescription(getContext(), description);
	}

	/**
	 * Set value of Description
	 * @param context
	 * @param description
	 */
	public final void setDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String description)
	{
		getMendixObject().setValue(context, MemberNames.Description.toString(), description);
	}

	/**
	 * @return value of StartTime
	 */
	public final java.util.Date getStartTime()
	{
		return getStartTime(getContext());
	}

	/**
	 * @param context
	 * @return value of StartTime
	 */
	public final java.util.Date getStartTime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.StartTime.toString());
	}

	/**
	 * Set value of StartTime
	 * @param starttime
	 */
	public final void setStartTime(java.util.Date starttime)
	{
		setStartTime(getContext(), starttime);
	}

	/**
	 * Set value of StartTime
	 * @param context
	 * @param starttime
	 */
	public final void setStartTime(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date starttime)
	{
		getMendixObject().setValue(context, MemberNames.StartTime.toString(), starttime);
	}

	/**
	 * @return value of EndTime
	 */
	public final java.util.Date getEndTime()
	{
		return getEndTime(getContext());
	}

	/**
	 * @param context
	 * @return value of EndTime
	 */
	public final java.util.Date getEndTime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.EndTime.toString());
	}

	/**
	 * Set value of EndTime
	 * @param endtime
	 */
	public final void setEndTime(java.util.Date endtime)
	{
		setEndTime(getContext(), endtime);
	}

	/**
	 * Set value of EndTime
	 * @param context
	 * @param endtime
	 */
	public final void setEndTime(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date endtime)
	{
		getMendixObject().setValue(context, MemberNames.EndTime.toString(), endtime);
	}

	/**
	 * @return value of DueDate
	 */
	public final java.util.Date getDueDate()
	{
		return getDueDate(getContext());
	}

	/**
	 * @param context
	 * @return value of DueDate
	 */
	public final java.util.Date getDueDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.DueDate.toString());
	}

	/**
	 * Set value of DueDate
	 * @param duedate
	 */
	public final void setDueDate(java.util.Date duedate)
	{
		setDueDate(getContext(), duedate);
	}

	/**
	 * Set value of DueDate
	 * @param context
	 * @param duedate
	 */
	public final void setDueDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date duedate)
	{
		getMendixObject().setValue(context, MemberNames.DueDate.toString(), duedate);
	}

	/**
	 * @return value of Outcome
	 */
	public final java.lang.String getOutcome()
	{
		return getOutcome(getContext());
	}

	/**
	 * @param context
	 * @return value of Outcome
	 */
	public final java.lang.String getOutcome(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Outcome.toString());
	}

	/**
	 * Set value of Outcome
	 * @param outcome
	 */
	public final void setOutcome(java.lang.String outcome)
	{
		setOutcome(getContext(), outcome);
	}

	/**
	 * Set value of Outcome
	 * @param context
	 * @param outcome
	 */
	public final void setOutcome(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String outcome)
	{
		getMendixObject().setValue(context, MemberNames.Outcome.toString(), outcome);
	}

	/**
	 * Get value of CompletionType
	 * @param completiontype
	 */
	public final system.proxies.WorkflowUserTaskCompletionType getCompletionType()
	{
		return getCompletionType(getContext());
	}

	/**
	 * @param context
	 * @return value of CompletionType
	 */
	public final system.proxies.WorkflowUserTaskCompletionType getCompletionType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.CompletionType.toString());
		if (obj == null) {
			return null;
		}
		return system.proxies.WorkflowUserTaskCompletionType.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of CompletionType
	 * @param completiontype
	 */
	public final void setCompletionType(system.proxies.WorkflowUserTaskCompletionType completiontype)
	{
		setCompletionType(getContext(), completiontype);
	}

	/**
	 * Set value of CompletionType
	 * @param context
	 * @param completiontype
	 */
	public final void setCompletionType(com.mendix.systemwideinterfaces.core.IContext context, system.proxies.WorkflowUserTaskCompletionType completiontype)
	{
		if (completiontype != null) {
			getMendixObject().setValue(context, MemberNames.CompletionType.toString(), completiontype.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.CompletionType.toString(), null);
		}
	}

	/**
	 * Get value of State
	 * @param state
	 */
	public final system.proxies.WorkflowUserTaskState getState()
	{
		return getState(getContext());
	}

	/**
	 * @param context
	 * @return value of State
	 */
	public final system.proxies.WorkflowUserTaskState getState(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.State.toString());
		if (obj == null) {
			return null;
		}
		return system.proxies.WorkflowUserTaskState.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of State
	 * @param state
	 */
	public final void setState(system.proxies.WorkflowUserTaskState state)
	{
		setState(getContext(), state);
	}

	/**
	 * Set value of State
	 * @param context
	 * @param state
	 */
	public final void setState(com.mendix.systemwideinterfaces.core.IContext context, system.proxies.WorkflowUserTaskState state)
	{
		if (state != null) {
			getMendixObject().setValue(context, MemberNames.State.toString(), state.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.State.toString(), null);
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of UserTaskView_WorkflowView
	 */
	public final workflowcommons.proxies.WorkflowView getUserTaskView_WorkflowView() throws com.mendix.core.CoreException
	{
		return getUserTaskView_WorkflowView(getContext());
	}

	/**
	 * @param context
	 * @return value of UserTaskView_WorkflowView
	 * @throws com.mendix.core.CoreException
	 */
	public final workflowcommons.proxies.WorkflowView getUserTaskView_WorkflowView(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		workflowcommons.proxies.WorkflowView result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.UserTaskView_WorkflowView.toString());
		if (identifier != null) {
			result = workflowcommons.proxies.WorkflowView.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of UserTaskView_WorkflowView
	 * @param usertaskview_workflowview
	 */
	public final void setUserTaskView_WorkflowView(workflowcommons.proxies.WorkflowView usertaskview_workflowview)
	{
		setUserTaskView_WorkflowView(getContext(), usertaskview_workflowview);
	}

	/**
	 * Set value of UserTaskView_WorkflowView
	 * @param context
	 * @param usertaskview_workflowview
	 */
	public final void setUserTaskView_WorkflowView(com.mendix.systemwideinterfaces.core.IContext context, workflowcommons.proxies.WorkflowView usertaskview_workflowview)
	{
		if (usertaskview_workflowview == null) {
			getMendixObject().setValue(context, MemberNames.UserTaskView_WorkflowView.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.UserTaskView_WorkflowView.toString(), usertaskview_workflowview.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of UserTaskView_WorkflowUserTask
	 */
	public final system.proxies.WorkflowUserTask getUserTaskView_WorkflowUserTask() throws com.mendix.core.CoreException
	{
		return getUserTaskView_WorkflowUserTask(getContext());
	}

	/**
	 * @param context
	 * @return value of UserTaskView_WorkflowUserTask
	 * @throws com.mendix.core.CoreException
	 */
	public final system.proxies.WorkflowUserTask getUserTaskView_WorkflowUserTask(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		system.proxies.WorkflowUserTask result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.UserTaskView_WorkflowUserTask.toString());
		if (identifier != null) {
			result = system.proxies.WorkflowUserTask.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of UserTaskView_WorkflowUserTask
	 * @param usertaskview_workflowusertask
	 */
	public final void setUserTaskView_WorkflowUserTask(system.proxies.WorkflowUserTask usertaskview_workflowusertask)
	{
		setUserTaskView_WorkflowUserTask(getContext(), usertaskview_workflowusertask);
	}

	/**
	 * Set value of UserTaskView_WorkflowUserTask
	 * @param context
	 * @param usertaskview_workflowusertask
	 */
	public final void setUserTaskView_WorkflowUserTask(com.mendix.systemwideinterfaces.core.IContext context, system.proxies.WorkflowUserTask usertaskview_workflowusertask)
	{
		if (usertaskview_workflowusertask == null) {
			getMendixObject().setValue(context, MemberNames.UserTaskView_WorkflowUserTask.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.UserTaskView_WorkflowUserTask.toString(), usertaskview_workflowusertask.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of UserTaskView_WorkflowUserTaskDefinition
	 */
	public final system.proxies.WorkflowUserTaskDefinition getUserTaskView_WorkflowUserTaskDefinition() throws com.mendix.core.CoreException
	{
		return getUserTaskView_WorkflowUserTaskDefinition(getContext());
	}

	/**
	 * @param context
	 * @return value of UserTaskView_WorkflowUserTaskDefinition
	 * @throws com.mendix.core.CoreException
	 */
	public final system.proxies.WorkflowUserTaskDefinition getUserTaskView_WorkflowUserTaskDefinition(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		system.proxies.WorkflowUserTaskDefinition result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.UserTaskView_WorkflowUserTaskDefinition.toString());
		if (identifier != null) {
			result = system.proxies.WorkflowUserTaskDefinition.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of UserTaskView_WorkflowUserTaskDefinition
	 * @param usertaskview_workflowusertaskdefinition
	 */
	public final void setUserTaskView_WorkflowUserTaskDefinition(system.proxies.WorkflowUserTaskDefinition usertaskview_workflowusertaskdefinition)
	{
		setUserTaskView_WorkflowUserTaskDefinition(getContext(), usertaskview_workflowusertaskdefinition);
	}

	/**
	 * Set value of UserTaskView_WorkflowUserTaskDefinition
	 * @param context
	 * @param usertaskview_workflowusertaskdefinition
	 */
	public final void setUserTaskView_WorkflowUserTaskDefinition(com.mendix.systemwideinterfaces.core.IContext context, system.proxies.WorkflowUserTaskDefinition usertaskview_workflowusertaskdefinition)
	{
		if (usertaskview_workflowusertaskdefinition == null) {
			getMendixObject().setValue(context, MemberNames.UserTaskView_WorkflowUserTaskDefinition.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.UserTaskView_WorkflowUserTaskDefinition.toString(), usertaskview_workflowusertaskdefinition.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of UserTaskView_Assignees
	 */
	public final java.util.List<system.proxies.User> getUserTaskView_Assignees() throws com.mendix.core.CoreException
	{
		return getUserTaskView_Assignees(getContext());
	}

	/**
	 * @param context
	 * @return value of UserTaskView_Assignees
	 * @throws com.mendix.core.CoreException
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<system.proxies.User> getUserTaskView_Assignees(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<system.proxies.User> result = new java.util.ArrayList<>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.UserTaskView_Assignees.toString());
		if (valueObject == null) {
			return result;
		}
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject)) {
			result.add(system.proxies.User.initialize(context, mendixObject));
		}
		return result;
	}

	/**
	 * Set value of UserTaskView_Assignees
	 * @param usertaskview_assignees
	 */
	public final void setUserTaskView_Assignees(java.util.List<system.proxies.User> usertaskview_assignees)
	{
		setUserTaskView_Assignees(getContext(), usertaskview_assignees);
	}

	/**
	 * Set value of UserTaskView_Assignees
	 * @param context
	 * @param usertaskview_assignees
	 */
	public final void setUserTaskView_Assignees(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<system.proxies.User> usertaskview_assignees)
	{
		var identifiers = usertaskview_assignees
			.stream()
			.map(proxyObject -> proxyObject.getMendixObject().getId())
			.collect(java.util.stream.Collectors.toList());
		
		getMendixObject().setValue(context, MemberNames.UserTaskView_Assignees.toString(), identifiers);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of UserTaskView_TargetUsers
	 */
	public final java.util.List<system.proxies.User> getUserTaskView_TargetUsers() throws com.mendix.core.CoreException
	{
		return getUserTaskView_TargetUsers(getContext());
	}

	/**
	 * @param context
	 * @return value of UserTaskView_TargetUsers
	 * @throws com.mendix.core.CoreException
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<system.proxies.User> getUserTaskView_TargetUsers(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<system.proxies.User> result = new java.util.ArrayList<>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.UserTaskView_TargetUsers.toString());
		if (valueObject == null) {
			return result;
		}
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject)) {
			result.add(system.proxies.User.initialize(context, mendixObject));
		}
		return result;
	}

	/**
	 * Set value of UserTaskView_TargetUsers
	 * @param usertaskview_targetusers
	 */
	public final void setUserTaskView_TargetUsers(java.util.List<system.proxies.User> usertaskview_targetusers)
	{
		setUserTaskView_TargetUsers(getContext(), usertaskview_targetusers);
	}

	/**
	 * Set value of UserTaskView_TargetUsers
	 * @param context
	 * @param usertaskview_targetusers
	 */
	public final void setUserTaskView_TargetUsers(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<system.proxies.User> usertaskview_targetusers)
	{
		var identifiers = usertaskview_targetusers
			.stream()
			.map(proxyObject -> proxyObject.getMendixObject().getId())
			.collect(java.util.stream.Collectors.toList());
		
		getMendixObject().setValue(context, MemberNames.UserTaskView_TargetUsers.toString(), identifiers);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of UserTaskView_Assignee
	 */
	public final system.proxies.User getUserTaskView_Assignee() throws com.mendix.core.CoreException
	{
		return getUserTaskView_Assignee(getContext());
	}

	/**
	 * @param context
	 * @return value of UserTaskView_Assignee
	 * @throws com.mendix.core.CoreException
	 */
	public final system.proxies.User getUserTaskView_Assignee(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		system.proxies.User result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.UserTaskView_Assignee.toString());
		if (identifier != null) {
			result = system.proxies.User.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of UserTaskView_Assignee
	 * @param usertaskview_assignee
	 */
	public final void setUserTaskView_Assignee(system.proxies.User usertaskview_assignee)
	{
		setUserTaskView_Assignee(getContext(), usertaskview_assignee);
	}

	/**
	 * Set value of UserTaskView_Assignee
	 * @param context
	 * @param usertaskview_assignee
	 */
	public final void setUserTaskView_Assignee(com.mendix.systemwideinterfaces.core.IContext context, system.proxies.User usertaskview_assignee)
	{
		if (usertaskview_assignee == null) {
			getMendixObject().setValue(context, MemberNames.UserTaskView_Assignee.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.UserTaskView_Assignee.toString(), usertaskview_assignee.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return userTaskViewMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final workflowcommons.proxies.UserTaskView that = (workflowcommons.proxies.UserTaskView) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
