// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package workflowcommons.proxies;

public class WorkflowSelectionHelper implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject workflowSelectionHelperMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "WorkflowCommons.WorkflowSelectionHelper";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		WorkflowSelectionHelper_WorkflowView("WorkflowCommons.WorkflowSelectionHelper_WorkflowView");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public WorkflowSelectionHelper(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected WorkflowSelectionHelper(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject workflowSelectionHelperMendixObject)
	{
		if (workflowSelectionHelperMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, workflowSelectionHelperMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.workflowSelectionHelperMendixObject = workflowSelectionHelperMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static workflowcommons.proxies.WorkflowSelectionHelper initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new workflowcommons.proxies.WorkflowSelectionHelper(context, mendixObject);
	}

	public static workflowcommons.proxies.WorkflowSelectionHelper load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return workflowcommons.proxies.WorkflowSelectionHelper.initialize(context, mendixObject);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of WorkflowSelectionHelper_WorkflowView
	 */
	public final workflowcommons.proxies.WorkflowView getWorkflowSelectionHelper_WorkflowView() throws com.mendix.core.CoreException
	{
		return getWorkflowSelectionHelper_WorkflowView(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkflowSelectionHelper_WorkflowView
	 * @throws com.mendix.core.CoreException
	 */
	public final workflowcommons.proxies.WorkflowView getWorkflowSelectionHelper_WorkflowView(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		workflowcommons.proxies.WorkflowView result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.WorkflowSelectionHelper_WorkflowView.toString());
		if (identifier != null) {
			result = workflowcommons.proxies.WorkflowView.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of WorkflowSelectionHelper_WorkflowView
	 * @param workflowselectionhelper_workflowview
	 */
	public final void setWorkflowSelectionHelper_WorkflowView(workflowcommons.proxies.WorkflowView workflowselectionhelper_workflowview)
	{
		setWorkflowSelectionHelper_WorkflowView(getContext(), workflowselectionhelper_workflowview);
	}

	/**
	 * Set value of WorkflowSelectionHelper_WorkflowView
	 * @param context
	 * @param workflowselectionhelper_workflowview
	 */
	public final void setWorkflowSelectionHelper_WorkflowView(com.mendix.systemwideinterfaces.core.IContext context, workflowcommons.proxies.WorkflowView workflowselectionhelper_workflowview)
	{
		if (workflowselectionhelper_workflowview == null) {
			getMendixObject().setValue(context, MemberNames.WorkflowSelectionHelper_WorkflowView.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.WorkflowSelectionHelper_WorkflowView.toString(), workflowselectionhelper_workflowview.getMendixObject().getId());
		}
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return workflowSelectionHelperMendixObject;
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final workflowcommons.proxies.WorkflowSelectionHelper that = (workflowcommons.proxies.WorkflowSelectionHelper) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
