// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package workflowcommons.proxies;

public class WorkflowSeries implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject workflowSeriesMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "WorkflowCommons.WorkflowSeries";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		DateDisplay("DateDisplay"),
		Date("Date"),
		NumberofWorkflowsCompleted("NumberofWorkflowsCompleted"),
		AverageWorkflowHandlingTime("AverageWorkflowHandlingTime"),
		NumberofWorkflowsCompletedOverdue("NumberofWorkflowsCompletedOverdue"),
		WorkflowSeries_DashboardContext("WorkflowCommons.WorkflowSeries_DashboardContext");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public WorkflowSeries(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected WorkflowSeries(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject workflowSeriesMendixObject)
	{
		if (workflowSeriesMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, workflowSeriesMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.workflowSeriesMendixObject = workflowSeriesMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static workflowcommons.proxies.WorkflowSeries initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new workflowcommons.proxies.WorkflowSeries(context, mendixObject);
	}

	public static workflowcommons.proxies.WorkflowSeries load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return workflowcommons.proxies.WorkflowSeries.initialize(context, mendixObject);
	}

	/**
	 * @return value of DateDisplay
	 */
	public final java.lang.String getDateDisplay()
	{
		return getDateDisplay(getContext());
	}

	/**
	 * @param context
	 * @return value of DateDisplay
	 */
	public final java.lang.String getDateDisplay(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.DateDisplay.toString());
	}

	/**
	 * Set value of DateDisplay
	 * @param datedisplay
	 */
	public final void setDateDisplay(java.lang.String datedisplay)
	{
		setDateDisplay(getContext(), datedisplay);
	}

	/**
	 * Set value of DateDisplay
	 * @param context
	 * @param datedisplay
	 */
	public final void setDateDisplay(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String datedisplay)
	{
		getMendixObject().setValue(context, MemberNames.DateDisplay.toString(), datedisplay);
	}

	/**
	 * @return value of Date
	 */
	public final java.util.Date getDate()
	{
		return getDate(getContext());
	}

	/**
	 * @param context
	 * @return value of Date
	 */
	public final java.util.Date getDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.Date.toString());
	}

	/**
	 * Set value of Date
	 * @param date
	 */
	public final void setDate(java.util.Date date)
	{
		setDate(getContext(), date);
	}

	/**
	 * Set value of Date
	 * @param context
	 * @param date
	 */
	public final void setDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date date)
	{
		getMendixObject().setValue(context, MemberNames.Date.toString(), date);
	}

	/**
	 * @return value of NumberofWorkflowsCompleted
	 */
	public final java.lang.Integer getNumberofWorkflowsCompleted()
	{
		return getNumberofWorkflowsCompleted(getContext());
	}

	/**
	 * @param context
	 * @return value of NumberofWorkflowsCompleted
	 */
	public final java.lang.Integer getNumberofWorkflowsCompleted(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.NumberofWorkflowsCompleted.toString());
	}

	/**
	 * Set value of NumberofWorkflowsCompleted
	 * @param numberofworkflowscompleted
	 */
	public final void setNumberofWorkflowsCompleted(java.lang.Integer numberofworkflowscompleted)
	{
		setNumberofWorkflowsCompleted(getContext(), numberofworkflowscompleted);
	}

	/**
	 * Set value of NumberofWorkflowsCompleted
	 * @param context
	 * @param numberofworkflowscompleted
	 */
	public final void setNumberofWorkflowsCompleted(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer numberofworkflowscompleted)
	{
		getMendixObject().setValue(context, MemberNames.NumberofWorkflowsCompleted.toString(), numberofworkflowscompleted);
	}

	/**
	 * @return value of AverageWorkflowHandlingTime
	 */
	public final java.math.BigDecimal getAverageWorkflowHandlingTime()
	{
		return getAverageWorkflowHandlingTime(getContext());
	}

	/**
	 * @param context
	 * @return value of AverageWorkflowHandlingTime
	 */
	public final java.math.BigDecimal getAverageWorkflowHandlingTime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.AverageWorkflowHandlingTime.toString());
	}

	/**
	 * Set value of AverageWorkflowHandlingTime
	 * @param averageworkflowhandlingtime
	 */
	public final void setAverageWorkflowHandlingTime(java.math.BigDecimal averageworkflowhandlingtime)
	{
		setAverageWorkflowHandlingTime(getContext(), averageworkflowhandlingtime);
	}

	/**
	 * Set value of AverageWorkflowHandlingTime
	 * @param context
	 * @param averageworkflowhandlingtime
	 */
	public final void setAverageWorkflowHandlingTime(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal averageworkflowhandlingtime)
	{
		getMendixObject().setValue(context, MemberNames.AverageWorkflowHandlingTime.toString(), averageworkflowhandlingtime);
	}

	/**
	 * @return value of NumberofWorkflowsCompletedOverdue
	 */
	public final java.lang.Integer getNumberofWorkflowsCompletedOverdue()
	{
		return getNumberofWorkflowsCompletedOverdue(getContext());
	}

	/**
	 * @param context
	 * @return value of NumberofWorkflowsCompletedOverdue
	 */
	public final java.lang.Integer getNumberofWorkflowsCompletedOverdue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.NumberofWorkflowsCompletedOverdue.toString());
	}

	/**
	 * Set value of NumberofWorkflowsCompletedOverdue
	 * @param numberofworkflowscompletedoverdue
	 */
	public final void setNumberofWorkflowsCompletedOverdue(java.lang.Integer numberofworkflowscompletedoverdue)
	{
		setNumberofWorkflowsCompletedOverdue(getContext(), numberofworkflowscompletedoverdue);
	}

	/**
	 * Set value of NumberofWorkflowsCompletedOverdue
	 * @param context
	 * @param numberofworkflowscompletedoverdue
	 */
	public final void setNumberofWorkflowsCompletedOverdue(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer numberofworkflowscompletedoverdue)
	{
		getMendixObject().setValue(context, MemberNames.NumberofWorkflowsCompletedOverdue.toString(), numberofworkflowscompletedoverdue);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of WorkflowSeries_DashboardContext
	 */
	public final workflowcommons.proxies.DashboardContext getWorkflowSeries_DashboardContext() throws com.mendix.core.CoreException
	{
		return getWorkflowSeries_DashboardContext(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkflowSeries_DashboardContext
	 * @throws com.mendix.core.CoreException
	 */
	public final workflowcommons.proxies.DashboardContext getWorkflowSeries_DashboardContext(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		workflowcommons.proxies.DashboardContext result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.WorkflowSeries_DashboardContext.toString());
		if (identifier != null) {
			result = workflowcommons.proxies.DashboardContext.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of WorkflowSeries_DashboardContext
	 * @param workflowseries_dashboardcontext
	 */
	public final void setWorkflowSeries_DashboardContext(workflowcommons.proxies.DashboardContext workflowseries_dashboardcontext)
	{
		setWorkflowSeries_DashboardContext(getContext(), workflowseries_dashboardcontext);
	}

	/**
	 * Set value of WorkflowSeries_DashboardContext
	 * @param context
	 * @param workflowseries_dashboardcontext
	 */
	public final void setWorkflowSeries_DashboardContext(com.mendix.systemwideinterfaces.core.IContext context, workflowcommons.proxies.DashboardContext workflowseries_dashboardcontext)
	{
		if (workflowseries_dashboardcontext == null) {
			getMendixObject().setValue(context, MemberNames.WorkflowSeries_DashboardContext.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.WorkflowSeries_DashboardContext.toString(), workflowseries_dashboardcontext.getMendixObject().getId());
		}
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return workflowSeriesMendixObject;
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final workflowcommons.proxies.WorkflowSeries that = (workflowcommons.proxies.WorkflowSeries) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
