// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package workflowcommons.proxies;

public class WorkflowComment
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject workflowCommentMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "WorkflowCommons.WorkflowComment";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Content("Content"),
		WorkflowComment_WorkflowView("WorkflowCommons.WorkflowComment_WorkflowView"),
		WorkflowComment_WorkflowComment("WorkflowCommons.WorkflowComment_WorkflowComment"),
		WorkflowComment_Workflow("WorkflowCommons.WorkflowComment_Workflow");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public WorkflowComment(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected WorkflowComment(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject workflowCommentMendixObject)
	{
		if (workflowCommentMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, workflowCommentMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.workflowCommentMendixObject = workflowCommentMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'WorkflowComment.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static workflowcommons.proxies.WorkflowComment initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return workflowcommons.proxies.WorkflowComment.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static workflowcommons.proxies.WorkflowComment initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new workflowcommons.proxies.WorkflowComment(context, mendixObject);
	}

	public static workflowcommons.proxies.WorkflowComment load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return workflowcommons.proxies.WorkflowComment.initialize(context, mendixObject);
	}

	public static java.util.List<workflowcommons.proxies.WorkflowComment> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> workflowcommons.proxies.WorkflowComment.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Content
	 */
	public final java.lang.String getContent()
	{
		return getContent(getContext());
	}

	/**
	 * @param context
	 * @return value of Content
	 */
	public final java.lang.String getContent(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Content.toString());
	}

	/**
	 * Set value of Content
	 * @param content
	 */
	public final void setContent(java.lang.String content)
	{
		setContent(getContext(), content);
	}

	/**
	 * Set value of Content
	 * @param context
	 * @param content
	 */
	public final void setContent(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String content)
	{
		getMendixObject().setValue(context, MemberNames.Content.toString(), content);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of WorkflowComment_WorkflowView
	 */
	public final workflowcommons.proxies.WorkflowView getWorkflowComment_WorkflowView() throws com.mendix.core.CoreException
	{
		return getWorkflowComment_WorkflowView(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkflowComment_WorkflowView
	 * @throws com.mendix.core.CoreException
	 */
	public final workflowcommons.proxies.WorkflowView getWorkflowComment_WorkflowView(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		workflowcommons.proxies.WorkflowView result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.WorkflowComment_WorkflowView.toString());
		if (identifier != null) {
			result = workflowcommons.proxies.WorkflowView.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of WorkflowComment_WorkflowView
	 * @param workflowcomment_workflowview
	 */
	public final void setWorkflowComment_WorkflowView(workflowcommons.proxies.WorkflowView workflowcomment_workflowview)
	{
		setWorkflowComment_WorkflowView(getContext(), workflowcomment_workflowview);
	}

	/**
	 * Set value of WorkflowComment_WorkflowView
	 * @param context
	 * @param workflowcomment_workflowview
	 */
	public final void setWorkflowComment_WorkflowView(com.mendix.systemwideinterfaces.core.IContext context, workflowcommons.proxies.WorkflowView workflowcomment_workflowview)
	{
		if (workflowcomment_workflowview == null) {
			getMendixObject().setValue(context, MemberNames.WorkflowComment_WorkflowView.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.WorkflowComment_WorkflowView.toString(), workflowcomment_workflowview.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of WorkflowComment_WorkflowComment
	 */
	public final workflowcommons.proxies.WorkflowComment getWorkflowComment_WorkflowComment() throws com.mendix.core.CoreException
	{
		return getWorkflowComment_WorkflowComment(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkflowComment_WorkflowComment
	 * @throws com.mendix.core.CoreException
	 */
	public final workflowcommons.proxies.WorkflowComment getWorkflowComment_WorkflowComment(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		workflowcommons.proxies.WorkflowComment result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.WorkflowComment_WorkflowComment.toString());
		if (identifier != null) {
			result = workflowcommons.proxies.WorkflowComment.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of WorkflowComment_WorkflowComment
	 * @param workflowcomment_workflowcomment
	 */
	public final void setWorkflowComment_WorkflowComment(workflowcommons.proxies.WorkflowComment workflowcomment_workflowcomment)
	{
		setWorkflowComment_WorkflowComment(getContext(), workflowcomment_workflowcomment);
	}

	/**
	 * Set value of WorkflowComment_WorkflowComment
	 * @param context
	 * @param workflowcomment_workflowcomment
	 */
	public final void setWorkflowComment_WorkflowComment(com.mendix.systemwideinterfaces.core.IContext context, workflowcommons.proxies.WorkflowComment workflowcomment_workflowcomment)
	{
		if (workflowcomment_workflowcomment == null) {
			getMendixObject().setValue(context, MemberNames.WorkflowComment_WorkflowComment.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.WorkflowComment_WorkflowComment.toString(), workflowcomment_workflowcomment.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of WorkflowComment_Workflow
	 */
	public final system.proxies.Workflow getWorkflowComment_Workflow() throws com.mendix.core.CoreException
	{
		return getWorkflowComment_Workflow(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkflowComment_Workflow
	 * @throws com.mendix.core.CoreException
	 */
	public final system.proxies.Workflow getWorkflowComment_Workflow(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		system.proxies.Workflow result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.WorkflowComment_Workflow.toString());
		if (identifier != null) {
			result = system.proxies.Workflow.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of WorkflowComment_Workflow
	 * @param workflowcomment_workflow
	 */
	public final void setWorkflowComment_Workflow(system.proxies.Workflow workflowcomment_workflow)
	{
		setWorkflowComment_Workflow(getContext(), workflowcomment_workflow);
	}

	/**
	 * Set value of WorkflowComment_Workflow
	 * @param context
	 * @param workflowcomment_workflow
	 */
	public final void setWorkflowComment_Workflow(com.mendix.systemwideinterfaces.core.IContext context, system.proxies.Workflow workflowcomment_workflow)
	{
		if (workflowcomment_workflow == null) {
			getMendixObject().setValue(context, MemberNames.WorkflowComment_Workflow.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.WorkflowComment_Workflow.toString(), workflowcomment_workflow.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return workflowCommentMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final workflowcommons.proxies.WorkflowComment that = (workflowcommons.proxies.WorkflowComment) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
