// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package workflowcommons.proxies;

public class WorkflowDefinitionHelper implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject workflowDefinitionHelperMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "WorkflowCommons.WorkflowDefinitionHelper";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		UpdateInstances("UpdateInstances"),
		WorkflowDefinitionHelper_WorkflowDefinition("WorkflowCommons.WorkflowDefinitionHelper_WorkflowDefinition");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public WorkflowDefinitionHelper(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected WorkflowDefinitionHelper(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject workflowDefinitionHelperMendixObject)
	{
		if (workflowDefinitionHelperMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, workflowDefinitionHelperMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.workflowDefinitionHelperMendixObject = workflowDefinitionHelperMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static workflowcommons.proxies.WorkflowDefinitionHelper initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new workflowcommons.proxies.WorkflowDefinitionHelper(context, mendixObject);
	}

	public static workflowcommons.proxies.WorkflowDefinitionHelper load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return workflowcommons.proxies.WorkflowDefinitionHelper.initialize(context, mendixObject);
	}

	/**
	 * @return value of UpdateInstances
	 */
	public final java.lang.Boolean getUpdateInstances()
	{
		return getUpdateInstances(getContext());
	}

	/**
	 * @param context
	 * @return value of UpdateInstances
	 */
	public final java.lang.Boolean getUpdateInstances(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.UpdateInstances.toString());
	}

	/**
	 * Set value of UpdateInstances
	 * @param updateinstances
	 */
	public final void setUpdateInstances(java.lang.Boolean updateinstances)
	{
		setUpdateInstances(getContext(), updateinstances);
	}

	/**
	 * Set value of UpdateInstances
	 * @param context
	 * @param updateinstances
	 */
	public final void setUpdateInstances(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean updateinstances)
	{
		getMendixObject().setValue(context, MemberNames.UpdateInstances.toString(), updateinstances);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of WorkflowDefinitionHelper_WorkflowDefinition
	 */
	public final system.proxies.WorkflowDefinition getWorkflowDefinitionHelper_WorkflowDefinition() throws com.mendix.core.CoreException
	{
		return getWorkflowDefinitionHelper_WorkflowDefinition(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkflowDefinitionHelper_WorkflowDefinition
	 * @throws com.mendix.core.CoreException
	 */
	public final system.proxies.WorkflowDefinition getWorkflowDefinitionHelper_WorkflowDefinition(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		system.proxies.WorkflowDefinition result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.WorkflowDefinitionHelper_WorkflowDefinition.toString());
		if (identifier != null) {
			result = system.proxies.WorkflowDefinition.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of WorkflowDefinitionHelper_WorkflowDefinition
	 * @param workflowdefinitionhelper_workflowdefinition
	 */
	public final void setWorkflowDefinitionHelper_WorkflowDefinition(system.proxies.WorkflowDefinition workflowdefinitionhelper_workflowdefinition)
	{
		setWorkflowDefinitionHelper_WorkflowDefinition(getContext(), workflowdefinitionhelper_workflowdefinition);
	}

	/**
	 * Set value of WorkflowDefinitionHelper_WorkflowDefinition
	 * @param context
	 * @param workflowdefinitionhelper_workflowdefinition
	 */
	public final void setWorkflowDefinitionHelper_WorkflowDefinition(com.mendix.systemwideinterfaces.core.IContext context, system.proxies.WorkflowDefinition workflowdefinitionhelper_workflowdefinition)
	{
		if (workflowdefinitionhelper_workflowdefinition == null) {
			getMendixObject().setValue(context, MemberNames.WorkflowDefinitionHelper_WorkflowDefinition.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.WorkflowDefinitionHelper_WorkflowDefinition.toString(), workflowdefinitionhelper_workflowdefinition.getMendixObject().getId());
		}
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return workflowDefinitionHelperMendixObject;
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final workflowcommons.proxies.WorkflowDefinitionHelper that = (workflowcommons.proxies.WorkflowDefinitionHelper) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
