// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package workflowcommons.proxies;

public class WorkflowCommentHelper implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject workflowCommentHelperMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "WorkflowCommons.WorkflowCommentHelper";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Content("Content"),
		WorkflowCommentHelper_WorkflowComment("WorkflowCommons.WorkflowCommentHelper_WorkflowComment");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public WorkflowCommentHelper(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected WorkflowCommentHelper(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject workflowCommentHelperMendixObject)
	{
		if (workflowCommentHelperMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, workflowCommentHelperMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.workflowCommentHelperMendixObject = workflowCommentHelperMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static workflowcommons.proxies.WorkflowCommentHelper initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new workflowcommons.proxies.WorkflowCommentHelper(context, mendixObject);
	}

	public static workflowcommons.proxies.WorkflowCommentHelper load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return workflowcommons.proxies.WorkflowCommentHelper.initialize(context, mendixObject);
	}

	/**
	 * @return value of Content
	 */
	public final java.lang.String getContent()
	{
		return getContent(getContext());
	}

	/**
	 * @param context
	 * @return value of Content
	 */
	public final java.lang.String getContent(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Content.toString());
	}

	/**
	 * Set value of Content
	 * @param content
	 */
	public final void setContent(java.lang.String content)
	{
		setContent(getContext(), content);
	}

	/**
	 * Set value of Content
	 * @param context
	 * @param content
	 */
	public final void setContent(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String content)
	{
		getMendixObject().setValue(context, MemberNames.Content.toString(), content);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of WorkflowCommentHelper_WorkflowComment
	 */
	public final workflowcommons.proxies.WorkflowComment getWorkflowCommentHelper_WorkflowComment() throws com.mendix.core.CoreException
	{
		return getWorkflowCommentHelper_WorkflowComment(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkflowCommentHelper_WorkflowComment
	 * @throws com.mendix.core.CoreException
	 */
	public final workflowcommons.proxies.WorkflowComment getWorkflowCommentHelper_WorkflowComment(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		workflowcommons.proxies.WorkflowComment result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.WorkflowCommentHelper_WorkflowComment.toString());
		if (identifier != null) {
			result = workflowcommons.proxies.WorkflowComment.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of WorkflowCommentHelper_WorkflowComment
	 * @param workflowcommenthelper_workflowcomment
	 */
	public final void setWorkflowCommentHelper_WorkflowComment(workflowcommons.proxies.WorkflowComment workflowcommenthelper_workflowcomment)
	{
		setWorkflowCommentHelper_WorkflowComment(getContext(), workflowcommenthelper_workflowcomment);
	}

	/**
	 * Set value of WorkflowCommentHelper_WorkflowComment
	 * @param context
	 * @param workflowcommenthelper_workflowcomment
	 */
	public final void setWorkflowCommentHelper_WorkflowComment(com.mendix.systemwideinterfaces.core.IContext context, workflowcommons.proxies.WorkflowComment workflowcommenthelper_workflowcomment)
	{
		if (workflowcommenthelper_workflowcomment == null) {
			getMendixObject().setValue(context, MemberNames.WorkflowCommentHelper_WorkflowComment.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.WorkflowCommentHelper_WorkflowComment.toString(), workflowcommenthelper_workflowcomment.getMendixObject().getId());
		}
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return workflowCommentHelperMendixObject;
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final workflowcommons.proxies.WorkflowCommentHelper that = (workflowcommons.proxies.WorkflowCommentHelper) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
