// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package taskqueuehelpers.proxies;

public class ProcessedQueueCount implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject processedQueueCountMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "TaskQueueHelpers.ProcessedQueueCount";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		QueueName("QueueName"),
		CompletedCount("CompletedCount"),
		UncompletedCount("UncompletedCount"),
		TotalCount("TotalCount");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ProcessedQueueCount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ProcessedQueueCount(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject processedQueueCountMendixObject)
	{
		if (processedQueueCountMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, processedQueueCountMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.processedQueueCountMendixObject = processedQueueCountMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static taskqueuehelpers.proxies.ProcessedQueueCount initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new taskqueuehelpers.proxies.ProcessedQueueCount(context, mendixObject);
	}

	public static taskqueuehelpers.proxies.ProcessedQueueCount load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return taskqueuehelpers.proxies.ProcessedQueueCount.initialize(context, mendixObject);
	}

	/**
	 * @return value of QueueName
	 */
	public final java.lang.String getQueueName()
	{
		return getQueueName(getContext());
	}

	/**
	 * @param context
	 * @return value of QueueName
	 */
	public final java.lang.String getQueueName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.QueueName.toString());
	}

	/**
	 * Set value of QueueName
	 * @param queuename
	 */
	public final void setQueueName(java.lang.String queuename)
	{
		setQueueName(getContext(), queuename);
	}

	/**
	 * Set value of QueueName
	 * @param context
	 * @param queuename
	 */
	public final void setQueueName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String queuename)
	{
		getMendixObject().setValue(context, MemberNames.QueueName.toString(), queuename);
	}

	/**
	 * @return value of CompletedCount
	 */
	public final java.lang.Long getCompletedCount()
	{
		return getCompletedCount(getContext());
	}

	/**
	 * @param context
	 * @return value of CompletedCount
	 */
	public final java.lang.Long getCompletedCount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.CompletedCount.toString());
	}

	/**
	 * Set value of CompletedCount
	 * @param completedcount
	 */
	public final void setCompletedCount(java.lang.Long completedcount)
	{
		setCompletedCount(getContext(), completedcount);
	}

	/**
	 * Set value of CompletedCount
	 * @param context
	 * @param completedcount
	 */
	public final void setCompletedCount(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long completedcount)
	{
		getMendixObject().setValue(context, MemberNames.CompletedCount.toString(), completedcount);
	}

	/**
	 * @return value of UncompletedCount
	 */
	public final java.lang.Long getUncompletedCount()
	{
		return getUncompletedCount(getContext());
	}

	/**
	 * @param context
	 * @return value of UncompletedCount
	 */
	public final java.lang.Long getUncompletedCount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.UncompletedCount.toString());
	}

	/**
	 * Set value of UncompletedCount
	 * @param uncompletedcount
	 */
	public final void setUncompletedCount(java.lang.Long uncompletedcount)
	{
		setUncompletedCount(getContext(), uncompletedcount);
	}

	/**
	 * Set value of UncompletedCount
	 * @param context
	 * @param uncompletedcount
	 */
	public final void setUncompletedCount(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long uncompletedcount)
	{
		getMendixObject().setValue(context, MemberNames.UncompletedCount.toString(), uncompletedcount);
	}

	/**
	 * @return value of TotalCount
	 */
	public final java.lang.Long getTotalCount()
	{
		return getTotalCount(getContext());
	}

	/**
	 * @param context
	 * @return value of TotalCount
	 */
	public final java.lang.Long getTotalCount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.TotalCount.toString());
	}

	/**
	 * Set value of TotalCount
	 * @param totalcount
	 */
	public final void setTotalCount(java.lang.Long totalcount)
	{
		setTotalCount(getContext(), totalcount);
	}

	/**
	 * Set value of TotalCount
	 * @param context
	 * @param totalcount
	 */
	public final void setTotalCount(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long totalcount)
	{
		getMendixObject().setValue(context, MemberNames.TotalCount.toString(), totalcount);
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return processedQueueCountMendixObject;
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final taskqueuehelpers.proxies.ProcessedQueueCount that = (taskqueuehelpers.proxies.ProcessedQueueCount) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
