// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package taskqueuehelpers.proxies;

public class ProcessedQueueCount
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject processedQueueCountMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "TaskQueueHelpers.ProcessedQueueCount";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		QueueName("QueueName"),
		CompletedCount("CompletedCount"),
		NonCompletedCount("NonCompletedCount");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ProcessedQueueCount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "TaskQueueHelpers.ProcessedQueueCount"));
	}

	protected ProcessedQueueCount(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject processedQueueCountMendixObject)
	{
		if (processedQueueCountMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("TaskQueueHelpers.ProcessedQueueCount", processedQueueCountMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a TaskQueueHelpers.ProcessedQueueCount");

		this.processedQueueCountMendixObject = processedQueueCountMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'ProcessedQueueCount.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static taskqueuehelpers.proxies.ProcessedQueueCount initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return taskqueuehelpers.proxies.ProcessedQueueCount.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static taskqueuehelpers.proxies.ProcessedQueueCount initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new taskqueuehelpers.proxies.ProcessedQueueCount(context, mendixObject);
	}

	public static taskqueuehelpers.proxies.ProcessedQueueCount load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return taskqueuehelpers.proxies.ProcessedQueueCount.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of QueueName
	 */
	public final java.lang.String getQueueName()
	{
		return getQueueName(getContext());
	}

	/**
	 * @param context
	 * @return value of QueueName
	 */
	public final java.lang.String getQueueName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.QueueName.toString());
	}

	/**
	 * Set value of QueueName
	 * @param queuename
	 */
	public final void setQueueName(java.lang.String queuename)
	{
		setQueueName(getContext(), queuename);
	}

	/**
	 * Set value of QueueName
	 * @param context
	 * @param queuename
	 */
	public final void setQueueName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String queuename)
	{
		getMendixObject().setValue(context, MemberNames.QueueName.toString(), queuename);
	}

	/**
	 * @return value of CompletedCount
	 */
	public final java.lang.Long getCompletedCount()
	{
		return getCompletedCount(getContext());
	}

	/**
	 * @param context
	 * @return value of CompletedCount
	 */
	public final java.lang.Long getCompletedCount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.CompletedCount.toString());
	}

	/**
	 * Set value of CompletedCount
	 * @param completedcount
	 */
	public final void setCompletedCount(java.lang.Long completedcount)
	{
		setCompletedCount(getContext(), completedcount);
	}

	/**
	 * Set value of CompletedCount
	 * @param context
	 * @param completedcount
	 */
	public final void setCompletedCount(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long completedcount)
	{
		getMendixObject().setValue(context, MemberNames.CompletedCount.toString(), completedcount);
	}

	/**
	 * @return value of NonCompletedCount
	 */
	public final java.lang.Long getNonCompletedCount()
	{
		return getNonCompletedCount(getContext());
	}

	/**
	 * @param context
	 * @return value of NonCompletedCount
	 */
	public final java.lang.Long getNonCompletedCount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.NonCompletedCount.toString());
	}

	/**
	 * Set value of NonCompletedCount
	 * @param noncompletedcount
	 */
	public final void setNonCompletedCount(java.lang.Long noncompletedcount)
	{
		setNonCompletedCount(getContext(), noncompletedcount);
	}

	/**
	 * Set value of NonCompletedCount
	 * @param context
	 * @param noncompletedcount
	 */
	public final void setNonCompletedCount(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long noncompletedcount)
	{
		getMendixObject().setValue(context, MemberNames.NonCompletedCount.toString(), noncompletedcount);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return processedQueueCountMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final taskqueuehelpers.proxies.ProcessedQueueCount that = (taskqueuehelpers.proxies.ProcessedQueueCount) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "TaskQueueHelpers.ProcessedQueueCount";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
