// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package system.proxies;

public class WorkflowRecord implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject workflowRecordMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "System.WorkflowRecord";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		WorkflowKey("WorkflowKey"),
		Name("Name"),
		Description("Description"),
		State("State"),
		StartTime("StartTime"),
		DueDate("DueDate"),
		EndTime("EndTime"),
		Reason("Reason"),
		WorkflowRecord_Workflow("System.WorkflowRecord_Workflow"),
		WorkflowRecord_Owner("System.WorkflowRecord_Owner"),
		WorkflowRecord_WorkflowDefinition("System.WorkflowRecord_WorkflowDefinition");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public WorkflowRecord(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected WorkflowRecord(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject workflowRecordMendixObject)
	{
		if (workflowRecordMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, workflowRecordMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.workflowRecordMendixObject = workflowRecordMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static system.proxies.WorkflowRecord initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new system.proxies.WorkflowRecord(context, mendixObject);
	}

	public static system.proxies.WorkflowRecord load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return system.proxies.WorkflowRecord.initialize(context, mendixObject);
	}

	/**
	 * @return value of WorkflowKey
	 */
	public final java.lang.String getWorkflowKey()
	{
		return getWorkflowKey(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkflowKey
	 */
	public final java.lang.String getWorkflowKey(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.WorkflowKey.toString());
	}

	/**
	 * Set value of WorkflowKey
	 * @param workflowkey
	 */
	public final void setWorkflowKey(java.lang.String workflowkey)
	{
		setWorkflowKey(getContext(), workflowkey);
	}

	/**
	 * Set value of WorkflowKey
	 * @param context
	 * @param workflowkey
	 */
	public final void setWorkflowKey(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String workflowkey)
	{
		getMendixObject().setValue(context, MemberNames.WorkflowKey.toString(), workflowkey);
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of Description
	 */
	public final java.lang.String getDescription()
	{
		return getDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of Description
	 */
	public final java.lang.String getDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Description.toString());
	}

	/**
	 * Set value of Description
	 * @param description
	 */
	public final void setDescription(java.lang.String description)
	{
		setDescription(getContext(), description);
	}

	/**
	 * Set value of Description
	 * @param context
	 * @param description
	 */
	public final void setDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String description)
	{
		getMendixObject().setValue(context, MemberNames.Description.toString(), description);
	}

	/**
	 * Get value of State
	 * @param state
	 */
	public final system.proxies.WorkflowState getState()
	{
		return getState(getContext());
	}

	/**
	 * @param context
	 * @return value of State
	 */
	public final system.proxies.WorkflowState getState(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.State.toString());
		if (obj == null) {
			return null;
		}
		return system.proxies.WorkflowState.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of State
	 * @param state
	 */
	public final void setState(system.proxies.WorkflowState state)
	{
		setState(getContext(), state);
	}

	/**
	 * Set value of State
	 * @param context
	 * @param state
	 */
	public final void setState(com.mendix.systemwideinterfaces.core.IContext context, system.proxies.WorkflowState state)
	{
		if (state != null) {
			getMendixObject().setValue(context, MemberNames.State.toString(), state.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.State.toString(), null);
		}
	}

	/**
	 * @return value of StartTime
	 */
	public final java.util.Date getStartTime()
	{
		return getStartTime(getContext());
	}

	/**
	 * @param context
	 * @return value of StartTime
	 */
	public final java.util.Date getStartTime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.StartTime.toString());
	}

	/**
	 * Set value of StartTime
	 * @param starttime
	 */
	public final void setStartTime(java.util.Date starttime)
	{
		setStartTime(getContext(), starttime);
	}

	/**
	 * Set value of StartTime
	 * @param context
	 * @param starttime
	 */
	public final void setStartTime(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date starttime)
	{
		getMendixObject().setValue(context, MemberNames.StartTime.toString(), starttime);
	}

	/**
	 * @return value of DueDate
	 */
	public final java.util.Date getDueDate()
	{
		return getDueDate(getContext());
	}

	/**
	 * @param context
	 * @return value of DueDate
	 */
	public final java.util.Date getDueDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.DueDate.toString());
	}

	/**
	 * Set value of DueDate
	 * @param duedate
	 */
	public final void setDueDate(java.util.Date duedate)
	{
		setDueDate(getContext(), duedate);
	}

	/**
	 * Set value of DueDate
	 * @param context
	 * @param duedate
	 */
	public final void setDueDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date duedate)
	{
		getMendixObject().setValue(context, MemberNames.DueDate.toString(), duedate);
	}

	/**
	 * @return value of EndTime
	 */
	public final java.util.Date getEndTime()
	{
		return getEndTime(getContext());
	}

	/**
	 * @param context
	 * @return value of EndTime
	 */
	public final java.util.Date getEndTime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.EndTime.toString());
	}

	/**
	 * Set value of EndTime
	 * @param endtime
	 */
	public final void setEndTime(java.util.Date endtime)
	{
		setEndTime(getContext(), endtime);
	}

	/**
	 * Set value of EndTime
	 * @param context
	 * @param endtime
	 */
	public final void setEndTime(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date endtime)
	{
		getMendixObject().setValue(context, MemberNames.EndTime.toString(), endtime);
	}

	/**
	 * @return value of Reason
	 */
	public final java.lang.String getReason()
	{
		return getReason(getContext());
	}

	/**
	 * @param context
	 * @return value of Reason
	 */
	public final java.lang.String getReason(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Reason.toString());
	}

	/**
	 * Set value of Reason
	 * @param reason
	 */
	public final void setReason(java.lang.String reason)
	{
		setReason(getContext(), reason);
	}

	/**
	 * Set value of Reason
	 * @param context
	 * @param reason
	 */
	public final void setReason(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String reason)
	{
		getMendixObject().setValue(context, MemberNames.Reason.toString(), reason);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of WorkflowRecord_Workflow
	 */
	public final system.proxies.Workflow getWorkflowRecord_Workflow() throws com.mendix.core.CoreException
	{
		return getWorkflowRecord_Workflow(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkflowRecord_Workflow
	 * @throws com.mendix.core.CoreException
	 */
	public final system.proxies.Workflow getWorkflowRecord_Workflow(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		system.proxies.Workflow result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.WorkflowRecord_Workflow.toString());
		if (identifier != null) {
			result = system.proxies.Workflow.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of WorkflowRecord_Workflow
	 * @param workflowrecord_workflow
	 */
	public final void setWorkflowRecord_Workflow(system.proxies.Workflow workflowrecord_workflow)
	{
		setWorkflowRecord_Workflow(getContext(), workflowrecord_workflow);
	}

	/**
	 * Set value of WorkflowRecord_Workflow
	 * @param context
	 * @param workflowrecord_workflow
	 */
	public final void setWorkflowRecord_Workflow(com.mendix.systemwideinterfaces.core.IContext context, system.proxies.Workflow workflowrecord_workflow)
	{
		if (workflowrecord_workflow == null) {
			getMendixObject().setValue(context, MemberNames.WorkflowRecord_Workflow.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.WorkflowRecord_Workflow.toString(), workflowrecord_workflow.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of WorkflowRecord_Owner
	 */
	public final system.proxies.User getWorkflowRecord_Owner() throws com.mendix.core.CoreException
	{
		return getWorkflowRecord_Owner(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkflowRecord_Owner
	 * @throws com.mendix.core.CoreException
	 */
	public final system.proxies.User getWorkflowRecord_Owner(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		system.proxies.User result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.WorkflowRecord_Owner.toString());
		if (identifier != null) {
			result = system.proxies.User.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of WorkflowRecord_Owner
	 * @param workflowrecord_owner
	 */
	public final void setWorkflowRecord_Owner(system.proxies.User workflowrecord_owner)
	{
		setWorkflowRecord_Owner(getContext(), workflowrecord_owner);
	}

	/**
	 * Set value of WorkflowRecord_Owner
	 * @param context
	 * @param workflowrecord_owner
	 */
	public final void setWorkflowRecord_Owner(com.mendix.systemwideinterfaces.core.IContext context, system.proxies.User workflowrecord_owner)
	{
		if (workflowrecord_owner == null) {
			getMendixObject().setValue(context, MemberNames.WorkflowRecord_Owner.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.WorkflowRecord_Owner.toString(), workflowrecord_owner.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of WorkflowRecord_WorkflowDefinition
	 */
	public final system.proxies.WorkflowDefinition getWorkflowRecord_WorkflowDefinition() throws com.mendix.core.CoreException
	{
		return getWorkflowRecord_WorkflowDefinition(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkflowRecord_WorkflowDefinition
	 * @throws com.mendix.core.CoreException
	 */
	public final system.proxies.WorkflowDefinition getWorkflowRecord_WorkflowDefinition(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		system.proxies.WorkflowDefinition result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.WorkflowRecord_WorkflowDefinition.toString());
		if (identifier != null) {
			result = system.proxies.WorkflowDefinition.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of WorkflowRecord_WorkflowDefinition
	 * @param workflowrecord_workflowdefinition
	 */
	public final void setWorkflowRecord_WorkflowDefinition(system.proxies.WorkflowDefinition workflowrecord_workflowdefinition)
	{
		setWorkflowRecord_WorkflowDefinition(getContext(), workflowrecord_workflowdefinition);
	}

	/**
	 * Set value of WorkflowRecord_WorkflowDefinition
	 * @param context
	 * @param workflowrecord_workflowdefinition
	 */
	public final void setWorkflowRecord_WorkflowDefinition(com.mendix.systemwideinterfaces.core.IContext context, system.proxies.WorkflowDefinition workflowrecord_workflowdefinition)
	{
		if (workflowrecord_workflowdefinition == null) {
			getMendixObject().setValue(context, MemberNames.WorkflowRecord_WorkflowDefinition.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.WorkflowRecord_WorkflowDefinition.toString(), workflowrecord_workflowdefinition.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return workflowRecordMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final system.proxies.WorkflowRecord that = (system.proxies.WorkflowRecord) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
