// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package workflowcommons.proxies;

public class WorkflowSummary
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject workflowSummaryMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "WorkflowCommons.WorkflowSummary";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		NumberOfWorkflowsCompleted("NumberOfWorkflowsCompleted"),
		NumberOfWorkflowsInProgress("NumberOfWorkflowsInProgress"),
		NumberOfWorkflowOverdue("NumberOfWorkflowOverdue"),
		NumberOfWorkflowsAborted("NumberOfWorkflowsAborted"),
		DashboardContext_WorkflowSummary("WorkflowCommons.DashboardContext_WorkflowSummary"),
		WorkflowSummary_WorkflowDefinition("WorkflowCommons.WorkflowSummary_WorkflowDefinition");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public WorkflowSummary(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "WorkflowCommons.WorkflowSummary"));
	}

	protected WorkflowSummary(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject workflowSummaryMendixObject)
	{
		if (workflowSummaryMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("WorkflowCommons.WorkflowSummary", workflowSummaryMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a WorkflowCommons.WorkflowSummary");

		this.workflowSummaryMendixObject = workflowSummaryMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'WorkflowSummary.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static workflowcommons.proxies.WorkflowSummary initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return workflowcommons.proxies.WorkflowSummary.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static workflowcommons.proxies.WorkflowSummary initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new workflowcommons.proxies.WorkflowSummary(context, mendixObject);
	}

	public static workflowcommons.proxies.WorkflowSummary load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return workflowcommons.proxies.WorkflowSummary.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of NumberOfWorkflowsCompleted
	 */
	public final java.lang.Integer getNumberOfWorkflowsCompleted()
	{
		return getNumberOfWorkflowsCompleted(getContext());
	}

	/**
	 * @param context
	 * @return value of NumberOfWorkflowsCompleted
	 */
	public final java.lang.Integer getNumberOfWorkflowsCompleted(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.NumberOfWorkflowsCompleted.toString());
	}

	/**
	 * Set value of NumberOfWorkflowsCompleted
	 * @param numberofworkflowscompleted
	 */
	public final void setNumberOfWorkflowsCompleted(java.lang.Integer numberofworkflowscompleted)
	{
		setNumberOfWorkflowsCompleted(getContext(), numberofworkflowscompleted);
	}

	/**
	 * Set value of NumberOfWorkflowsCompleted
	 * @param context
	 * @param numberofworkflowscompleted
	 */
	public final void setNumberOfWorkflowsCompleted(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer numberofworkflowscompleted)
	{
		getMendixObject().setValue(context, MemberNames.NumberOfWorkflowsCompleted.toString(), numberofworkflowscompleted);
	}

	/**
	 * @return value of NumberOfWorkflowsInProgress
	 */
	public final java.lang.Integer getNumberOfWorkflowsInProgress()
	{
		return getNumberOfWorkflowsInProgress(getContext());
	}

	/**
	 * @param context
	 * @return value of NumberOfWorkflowsInProgress
	 */
	public final java.lang.Integer getNumberOfWorkflowsInProgress(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.NumberOfWorkflowsInProgress.toString());
	}

	/**
	 * Set value of NumberOfWorkflowsInProgress
	 * @param numberofworkflowsinprogress
	 */
	public final void setNumberOfWorkflowsInProgress(java.lang.Integer numberofworkflowsinprogress)
	{
		setNumberOfWorkflowsInProgress(getContext(), numberofworkflowsinprogress);
	}

	/**
	 * Set value of NumberOfWorkflowsInProgress
	 * @param context
	 * @param numberofworkflowsinprogress
	 */
	public final void setNumberOfWorkflowsInProgress(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer numberofworkflowsinprogress)
	{
		getMendixObject().setValue(context, MemberNames.NumberOfWorkflowsInProgress.toString(), numberofworkflowsinprogress);
	}

	/**
	 * @return value of NumberOfWorkflowOverdue
	 */
	public final java.lang.Integer getNumberOfWorkflowOverdue()
	{
		return getNumberOfWorkflowOverdue(getContext());
	}

	/**
	 * @param context
	 * @return value of NumberOfWorkflowOverdue
	 */
	public final java.lang.Integer getNumberOfWorkflowOverdue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.NumberOfWorkflowOverdue.toString());
	}

	/**
	 * Set value of NumberOfWorkflowOverdue
	 * @param numberofworkflowoverdue
	 */
	public final void setNumberOfWorkflowOverdue(java.lang.Integer numberofworkflowoverdue)
	{
		setNumberOfWorkflowOverdue(getContext(), numberofworkflowoverdue);
	}

	/**
	 * Set value of NumberOfWorkflowOverdue
	 * @param context
	 * @param numberofworkflowoverdue
	 */
	public final void setNumberOfWorkflowOverdue(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer numberofworkflowoverdue)
	{
		getMendixObject().setValue(context, MemberNames.NumberOfWorkflowOverdue.toString(), numberofworkflowoverdue);
	}

	/**
	 * @return value of NumberOfWorkflowsAborted
	 */
	public final java.lang.Integer getNumberOfWorkflowsAborted()
	{
		return getNumberOfWorkflowsAborted(getContext());
	}

	/**
	 * @param context
	 * @return value of NumberOfWorkflowsAborted
	 */
	public final java.lang.Integer getNumberOfWorkflowsAborted(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.NumberOfWorkflowsAborted.toString());
	}

	/**
	 * Set value of NumberOfWorkflowsAborted
	 * @param numberofworkflowsaborted
	 */
	public final void setNumberOfWorkflowsAborted(java.lang.Integer numberofworkflowsaborted)
	{
		setNumberOfWorkflowsAborted(getContext(), numberofworkflowsaborted);
	}

	/**
	 * Set value of NumberOfWorkflowsAborted
	 * @param context
	 * @param numberofworkflowsaborted
	 */
	public final void setNumberOfWorkflowsAborted(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer numberofworkflowsaborted)
	{
		getMendixObject().setValue(context, MemberNames.NumberOfWorkflowsAborted.toString(), numberofworkflowsaborted);
	}

	/**
	 * @return value of DashboardContext_WorkflowSummary
	 */
	public final workflowcommons.proxies.DashboardContext getDashboardContext_WorkflowSummary() throws com.mendix.core.CoreException
	{
		return getDashboardContext_WorkflowSummary(getContext());
	}

	/**
	 * @param context
	 * @return value of DashboardContext_WorkflowSummary
	 */
	public final workflowcommons.proxies.DashboardContext getDashboardContext_WorkflowSummary(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		workflowcommons.proxies.DashboardContext result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.DashboardContext_WorkflowSummary.toString());
		if (identifier != null)
			result = workflowcommons.proxies.DashboardContext.load(context, identifier);
		return result;
	}

	/**
	 * Set value of DashboardContext_WorkflowSummary
	 * @param dashboardcontext_workflowsummary
	 */
	public final void setDashboardContext_WorkflowSummary(workflowcommons.proxies.DashboardContext dashboardcontext_workflowsummary)
	{
		setDashboardContext_WorkflowSummary(getContext(), dashboardcontext_workflowsummary);
	}

	/**
	 * Set value of DashboardContext_WorkflowSummary
	 * @param context
	 * @param dashboardcontext_workflowsummary
	 */
	public final void setDashboardContext_WorkflowSummary(com.mendix.systemwideinterfaces.core.IContext context, workflowcommons.proxies.DashboardContext dashboardcontext_workflowsummary)
	{
		if (dashboardcontext_workflowsummary == null)
			getMendixObject().setValue(context, MemberNames.DashboardContext_WorkflowSummary.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.DashboardContext_WorkflowSummary.toString(), dashboardcontext_workflowsummary.getMendixObject().getId());
	}

	/**
	 * @return value of WorkflowSummary_WorkflowDefinition
	 */
	public final system.proxies.WorkflowDefinition getWorkflowSummary_WorkflowDefinition() throws com.mendix.core.CoreException
	{
		return getWorkflowSummary_WorkflowDefinition(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkflowSummary_WorkflowDefinition
	 */
	public final system.proxies.WorkflowDefinition getWorkflowSummary_WorkflowDefinition(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		system.proxies.WorkflowDefinition result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.WorkflowSummary_WorkflowDefinition.toString());
		if (identifier != null)
			result = system.proxies.WorkflowDefinition.load(context, identifier);
		return result;
	}

	/**
	 * Set value of WorkflowSummary_WorkflowDefinition
	 * @param workflowsummary_workflowdefinition
	 */
	public final void setWorkflowSummary_WorkflowDefinition(system.proxies.WorkflowDefinition workflowsummary_workflowdefinition)
	{
		setWorkflowSummary_WorkflowDefinition(getContext(), workflowsummary_workflowdefinition);
	}

	/**
	 * Set value of WorkflowSummary_WorkflowDefinition
	 * @param context
	 * @param workflowsummary_workflowdefinition
	 */
	public final void setWorkflowSummary_WorkflowDefinition(com.mendix.systemwideinterfaces.core.IContext context, system.proxies.WorkflowDefinition workflowsummary_workflowdefinition)
	{
		if (workflowsummary_workflowdefinition == null)
			getMendixObject().setValue(context, MemberNames.WorkflowSummary_WorkflowDefinition.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.WorkflowSummary_WorkflowDefinition.toString(), workflowsummary_workflowdefinition.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return workflowSummaryMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final workflowcommons.proxies.WorkflowSummary that = (workflowcommons.proxies.WorkflowSummary) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "WorkflowCommons.WorkflowSummary";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
