// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package workflowcommons.proxies;

public class WorkflowCommentHelper
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject workflowCommentHelperMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "WorkflowCommons.WorkflowCommentHelper";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Content("Content"),
		EditMode("EditMode"),
		WorkflowCommentHelper_WorkflowComment("WorkflowCommons.WorkflowCommentHelper_WorkflowComment");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public WorkflowCommentHelper(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "WorkflowCommons.WorkflowCommentHelper"));
	}

	protected WorkflowCommentHelper(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject workflowCommentHelperMendixObject)
	{
		if (workflowCommentHelperMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("WorkflowCommons.WorkflowCommentHelper", workflowCommentHelperMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a WorkflowCommons.WorkflowCommentHelper");

		this.workflowCommentHelperMendixObject = workflowCommentHelperMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'WorkflowCommentHelper.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static workflowcommons.proxies.WorkflowCommentHelper initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return workflowcommons.proxies.WorkflowCommentHelper.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static workflowcommons.proxies.WorkflowCommentHelper initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new workflowcommons.proxies.WorkflowCommentHelper(context, mendixObject);
	}

	public static workflowcommons.proxies.WorkflowCommentHelper load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return workflowcommons.proxies.WorkflowCommentHelper.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Content
	 */
	public final java.lang.String getContent()
	{
		return getContent(getContext());
	}

	/**
	 * @param context
	 * @return value of Content
	 */
	public final java.lang.String getContent(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Content.toString());
	}

	/**
	 * Set value of Content
	 * @param content
	 */
	public final void setContent(java.lang.String content)
	{
		setContent(getContext(), content);
	}

	/**
	 * Set value of Content
	 * @param context
	 * @param content
	 */
	public final void setContent(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String content)
	{
		getMendixObject().setValue(context, MemberNames.Content.toString(), content);
	}

	/**
	 * @return value of EditMode
	 */
	public final java.lang.Boolean getEditMode()
	{
		return getEditMode(getContext());
	}

	/**
	 * @param context
	 * @return value of EditMode
	 */
	public final java.lang.Boolean getEditMode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.EditMode.toString());
	}

	/**
	 * Set value of EditMode
	 * @param editmode
	 */
	public final void setEditMode(java.lang.Boolean editmode)
	{
		setEditMode(getContext(), editmode);
	}

	/**
	 * Set value of EditMode
	 * @param context
	 * @param editmode
	 */
	public final void setEditMode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean editmode)
	{
		getMendixObject().setValue(context, MemberNames.EditMode.toString(), editmode);
	}

	/**
	 * @return value of WorkflowCommentHelper_WorkflowComment
	 */
	public final workflowcommons.proxies.WorkflowComment getWorkflowCommentHelper_WorkflowComment() throws com.mendix.core.CoreException
	{
		return getWorkflowCommentHelper_WorkflowComment(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkflowCommentHelper_WorkflowComment
	 */
	public final workflowcommons.proxies.WorkflowComment getWorkflowCommentHelper_WorkflowComment(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		workflowcommons.proxies.WorkflowComment result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.WorkflowCommentHelper_WorkflowComment.toString());
		if (identifier != null)
			result = workflowcommons.proxies.WorkflowComment.load(context, identifier);
		return result;
	}

	/**
	 * Set value of WorkflowCommentHelper_WorkflowComment
	 * @param workflowcommenthelper_workflowcomment
	 */
	public final void setWorkflowCommentHelper_WorkflowComment(workflowcommons.proxies.WorkflowComment workflowcommenthelper_workflowcomment)
	{
		setWorkflowCommentHelper_WorkflowComment(getContext(), workflowcommenthelper_workflowcomment);
	}

	/**
	 * Set value of WorkflowCommentHelper_WorkflowComment
	 * @param context
	 * @param workflowcommenthelper_workflowcomment
	 */
	public final void setWorkflowCommentHelper_WorkflowComment(com.mendix.systemwideinterfaces.core.IContext context, workflowcommons.proxies.WorkflowComment workflowcommenthelper_workflowcomment)
	{
		if (workflowcommenthelper_workflowcomment == null)
			getMendixObject().setValue(context, MemberNames.WorkflowCommentHelper_WorkflowComment.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.WorkflowCommentHelper_WorkflowComment.toString(), workflowcommenthelper_workflowcomment.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return workflowCommentHelperMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final workflowcommons.proxies.WorkflowCommentHelper that = (workflowcommons.proxies.WorkflowCommentHelper) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "WorkflowCommons.WorkflowCommentHelper";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
