// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package expenserequestexample.proxies;

public class ExpenseRequestWorkflow extends system.proxies.Workflow
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "ExpenseRequestExample.ExpenseRequestWorkflow";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		Description("Description"),
		StartTime("StartTime"),
		EndTime("EndTime"),
		DueDate("DueDate"),
		CanBeRestarted("CanBeRestarted"),
		CanBeContinued("CanBeContinued"),
		State("State"),
		Reason("Reason"),
		ExpenseRequestWorkflow_ExpenseRequest("ExpenseRequestExample.ExpenseRequestWorkflow_ExpenseRequest"),
		Workflow_WorkflowDefinition("System.Workflow_WorkflowDefinition");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ExpenseRequestWorkflow(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "ExpenseRequestExample.ExpenseRequestWorkflow"));
	}

	protected ExpenseRequestWorkflow(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject expenseRequestWorkflowMendixObject)
	{
		super(context, expenseRequestWorkflowMendixObject);
		if (!com.mendix.core.Core.isSubClassOf("ExpenseRequestExample.ExpenseRequestWorkflow", expenseRequestWorkflowMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a ExpenseRequestExample.ExpenseRequestWorkflow");
	}

	/**
	 * @deprecated Use 'ExpenseRequestWorkflow.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static expenserequestexample.proxies.ExpenseRequestWorkflow initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return expenserequestexample.proxies.ExpenseRequestWorkflow.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static expenserequestexample.proxies.ExpenseRequestWorkflow initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new expenserequestexample.proxies.ExpenseRequestWorkflow(context, mendixObject);
	}

	public static expenserequestexample.proxies.ExpenseRequestWorkflow load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return expenserequestexample.proxies.ExpenseRequestWorkflow.initialize(context, mendixObject);
	}

	public static java.util.List<expenserequestexample.proxies.ExpenseRequestWorkflow> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<expenserequestexample.proxies.ExpenseRequestWorkflow> result = new java.util.ArrayList<expenserequestexample.proxies.ExpenseRequestWorkflow>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//ExpenseRequestExample.ExpenseRequestWorkflow" + xpathConstraint))
			result.add(expenserequestexample.proxies.ExpenseRequestWorkflow.initialize(context, obj));
		return result;
	}

	/**
	 * @return value of ExpenseRequestWorkflow_ExpenseRequest
	 */
	public final expenserequestexample.proxies.ExpenseRequest getExpenseRequestWorkflow_ExpenseRequest() throws com.mendix.core.CoreException
	{
		return getExpenseRequestWorkflow_ExpenseRequest(getContext());
	}

	/**
	 * @param context
	 * @return value of ExpenseRequestWorkflow_ExpenseRequest
	 */
	public final expenserequestexample.proxies.ExpenseRequest getExpenseRequestWorkflow_ExpenseRequest(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		expenserequestexample.proxies.ExpenseRequest result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ExpenseRequestWorkflow_ExpenseRequest.toString());
		if (identifier != null)
			result = expenserequestexample.proxies.ExpenseRequest.load(context, identifier);
		return result;
	}

	/**
	 * Set value of ExpenseRequestWorkflow_ExpenseRequest
	 * @param expenserequestworkflow_expenserequest
	 */
	public final void setExpenseRequestWorkflow_ExpenseRequest(expenserequestexample.proxies.ExpenseRequest expenserequestworkflow_expenserequest)
	{
		setExpenseRequestWorkflow_ExpenseRequest(getContext(), expenserequestworkflow_expenserequest);
	}

	/**
	 * Set value of ExpenseRequestWorkflow_ExpenseRequest
	 * @param context
	 * @param expenserequestworkflow_expenserequest
	 */
	public final void setExpenseRequestWorkflow_ExpenseRequest(com.mendix.systemwideinterfaces.core.IContext context, expenserequestexample.proxies.ExpenseRequest expenserequestworkflow_expenserequest)
	{
		if (expenserequestworkflow_expenserequest == null)
			getMendixObject().setValue(context, MemberNames.ExpenseRequestWorkflow_ExpenseRequest.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.ExpenseRequestWorkflow_ExpenseRequest.toString(), expenserequestworkflow_expenserequest.getMendixObject().getId());
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final expenserequestexample.proxies.ExpenseRequestWorkflow that = (expenserequestexample.proxies.ExpenseRequestWorkflow) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "ExpenseRequestExample.ExpenseRequestWorkflow";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
