// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package workflowcommons.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the microflows for the WorkflowCommons module
	public static void aCT_Attachment_Create(IContext context, system.proxies.Workflow _workflow)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Workflow", _workflow == null ? null : _workflow.getMendixObject());
		Core.microflowCall("WorkflowCommons.ACT_Attachment_Create").withParams(params).execute(context);
	}
	public static void aCT_Attachment_Download(IContext context, system.proxies.FileDocument _fileDoc)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("FileDoc", _fileDoc == null ? null : _fileDoc.getMendixObject());
		Core.microflowCall("WorkflowCommons.ACT_Attachment_Download").withParams(params).execute(context);
	}
	public static void aCT_Attachment_Save(IContext context, workflowcommons.proxies.WorkflowAttachment _workflowAttachment)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("WorkflowAttachment", _workflowAttachment == null ? null : _workflowAttachment.getMendixObject());
		Core.microflowCall("WorkflowCommons.ACT_Attachment_Save").withParams(params).execute(context);
	}
	public static void aCT_Comment_Delete(IContext context, workflowcommons.proxies.WorkflowComment _workflowComment)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("WorkflowComment", _workflowComment == null ? null : _workflowComment.getMendixObject());
		Core.microflowCall("WorkflowCommons.ACT_Comment_Delete").withParams(params).execute(context);
	}
	public static void aCT_DashboardContext_Refresh(IContext context, workflowcommons.proxies.DashboardContext _dashboardContext)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("DashboardContext", _dashboardContext == null ? null : _dashboardContext.getMendixObject());
		Core.microflowCall("WorkflowCommons.ACT_DashboardContext_Refresh").withParams(params).execute(context);
	}
	public static boolean aCT_TaskCount_Refresh(IContext context, workflowcommons.proxies.TaskCount _taskCount)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("TaskCount", _taskCount == null ? null : _taskCount.getMendixObject());
		return (java.lang.Boolean) Core.microflowCall("WorkflowCommons.ACT_TaskCount_Refresh").withParams(params).execute(context);
	}
	public static void aCT_UserTask_AssignToMe(IContext context, system.proxies.WorkflowUserTask _workflowUserTask)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("WorkflowUserTask", _workflowUserTask == null ? null : _workflowUserTask.getMendixObject());
		Core.microflowCall("WorkflowCommons.ACT_UserTask_AssignToMe").withParams(params).execute(context);
	}
	public static void aCT_UserTask_AssignToMe_UpdateTaskCount(IContext context, system.proxies.WorkflowUserTask _userTask, workflowcommons.proxies.TaskCount _taskCount)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("UserTask", _userTask == null ? null : _userTask.getMendixObject());
		params.put("TaskCount", _taskCount == null ? null : _taskCount.getMendixObject());
		Core.microflowCall("WorkflowCommons.ACT_UserTask_AssignToMe_UpdateTaskCount").withParams(params).execute(context);
	}
	public static void aCT_UserTask_AssignToUser(IContext context, system.proxies.WorkflowUserTask _workflowUserTask, system.proxies.User _user)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("WorkflowUserTask", _workflowUserTask == null ? null : _workflowUserTask.getMendixObject());
		params.put("User", _user == null ? null : _user.getMendixObject());
		Core.microflowCall("WorkflowCommons.ACT_UserTask_AssignToUser").withParams(params).execute(context);
	}
	public static void aCT_UserTask_ShowDefaultAdminPage(IContext context, system.proxies.WorkflowUserTask _workflowUserTask)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("WorkflowUserTask", _workflowUserTask == null ? null : _workflowUserTask.getMendixObject());
		Core.microflowCall("WorkflowCommons.ACT_UserTask_ShowDefaultAdminPage").withParams(params).execute(context);
	}
	public static void aCT_UserTask_ShowUserTaskPage(IContext context, system.proxies.WorkflowUserTask _workflowUserTask)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("WorkflowUserTask", _workflowUserTask == null ? null : _workflowUserTask.getMendixObject());
		Core.microflowCall("WorkflowCommons.ACT_UserTask_ShowUserTaskPage").withParams(params).execute(context);
	}
	public static void aCT_UserTask_Unassign(IContext context, system.proxies.WorkflowUserTask _userTask)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("UserTask", _userTask == null ? null : _userTask.getMendixObject());
		Core.microflowCall("WorkflowCommons.ACT_UserTask_Unassign").withParams(params).execute(context);
	}
	public static void aCT_Workflow_Abort(IContext context, system.proxies.Workflow _workflow)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Workflow", _workflow == null ? null : _workflow.getMendixObject());
		Core.microflowCall("WorkflowCommons.ACT_Workflow_Abort").withParams(params).execute(context);
	}
	public static void aCT_Workflow_Continue(IContext context, system.proxies.Workflow _workflow)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Workflow", _workflow == null ? null : _workflow.getMendixObject());
		Core.microflowCall("WorkflowCommons.ACT_Workflow_Continue").withParams(params).execute(context);
	}
	public static void aCT_Workflow_Pause(IContext context, system.proxies.Workflow _workflow)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Workflow", _workflow == null ? null : _workflow.getMendixObject());
		Core.microflowCall("WorkflowCommons.ACT_Workflow_Pause").withParams(params).execute(context);
	}
	public static void aCT_Workflow_Restart(IContext context, system.proxies.Workflow _workflow)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Workflow", _workflow == null ? null : _workflow.getMendixObject());
		Core.microflowCall("WorkflowCommons.ACT_Workflow_Restart").withParams(params).execute(context);
	}
	public static void aCT_Workflow_Resume(IContext context, system.proxies.Workflow _workflow)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Workflow", _workflow == null ? null : _workflow.getMendixObject());
		Core.microflowCall("WorkflowCommons.ACT_Workflow_Resume").withParams(params).execute(context);
	}
	public static void aCT_Workflow_ShowWorkflowAdminPage(IContext context, system.proxies.Workflow _workflow)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Workflow", _workflow == null ? null : _workflow.getMendixObject());
		Core.microflowCall("WorkflowCommons.ACT_Workflow_ShowWorkflowAdminPage").withParams(params).execute(context);
	}
	public static void aCT_WorkflowCommentHelper_SaveNew(IContext context, workflowcommons.proxies.WorkflowCommentHelper _workflowCommentHelper, system.proxies.Workflow _workflow)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("WorkflowCommentHelper", _workflowCommentHelper == null ? null : _workflowCommentHelper.getMendixObject());
		params.put("Workflow", _workflow == null ? null : _workflow.getMendixObject());
		Core.microflowCall("WorkflowCommons.ACT_WorkflowCommentHelper_SaveNew").withParams(params).execute(context);
	}
	public static void aCT_WorkflowDefinition_DeleteAllWorkflows(IContext context, system.proxies.WorkflowDefinition _workflowDefinition)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("WorkflowDefinition", _workflowDefinition == null ? null : _workflowDefinition.getMendixObject());
		Core.microflowCall("WorkflowCommons.ACT_WorkflowDefinition_DeleteAllWorkflows").withParams(params).execute(context);
	}
	public static void aCT_WorkflowUserTask_AssignUser(IContext context, system.proxies.User _user, system.proxies.WorkflowUserTask _workflowUserTask)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("User", _user == null ? null : _user.getMendixObject());
		params.put("WorkflowUserTask", _workflowUserTask == null ? null : _workflowUserTask.getMendixObject());
		Core.microflowCall("WorkflowCommons.ACT_WorkflowUserTask_AssignUser").withParams(params).execute(context);
	}
	public static workflowcommons.proxies.TaskCount dS_TaskCount(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("WorkflowCommons.DS_TaskCount").withParams(params).execute(context);
		return result == null ? null : workflowcommons.proxies.TaskCount.initialize(context, result);
	}
	public static java.util.List<system.proxies.Workflow> dS_Workflow(IContext context, workflowcommons.proxies.DashboardContext _dashboardContext)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("DashboardContext", _dashboardContext == null ? null : _dashboardContext.getMendixObject());
		java.util.List<IMendixObject> objs = Core.microflowCall("WorkflowCommons.DS_Workflow").withParams(params).execute(context);
		java.util.List<system.proxies.Workflow> result = null;
		if (objs != null)
		{
			result = new java.util.ArrayList<>();
			for (IMendixObject obj : objs)
				result.add(system.proxies.Workflow.initialize(context, obj));
		}
		return result;
	}
	public static workflowcommons.proxies.WorkflowCommentHelper dS_WorkflowCommentHelper_InitializeNew(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("WorkflowCommons.DS_WorkflowCommentHelper_InitializeNew").withParams(params).execute(context);
		return result == null ? null : workflowcommons.proxies.WorkflowCommentHelper.initialize(context, result);
	}
	public static workflowcommons.proxies.DashboardContext dS_WorkflowDashboard(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("WorkflowCommons.DS_WorkflowDashboard").withParams(params).execute(context);
		return result == null ? null : workflowcommons.proxies.DashboardContext.initialize(context, result);
	}
	public static java.util.List<workflowcommons.proxies.WorkflowSummary> dS_WorkflowDefinition_Overview(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		java.util.List<IMendixObject> objs = Core.microflowCall("WorkflowCommons.DS_WorkflowDefinition_Overview").withParams(params).execute(context);
		java.util.List<workflowcommons.proxies.WorkflowSummary> result = null;
		if (objs != null)
		{
			result = new java.util.ArrayList<>();
			for (IMendixObject obj : objs)
				result.add(workflowcommons.proxies.WorkflowSummary.initialize(context, obj));
		}
		return result;
	}
	public static java.util.List<workflowcommons.proxies.WorkflowSeries> dS_WorkflowSeries(IContext context, workflowcommons.proxies.DashboardContext _dashboardContext)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("DashboardContext", _dashboardContext == null ? null : _dashboardContext.getMendixObject());
		java.util.List<IMendixObject> objs = Core.microflowCall("WorkflowCommons.DS_WorkflowSeries").withParams(params).execute(context);
		java.util.List<workflowcommons.proxies.WorkflowSeries> result = null;
		if (objs != null)
		{
			result = new java.util.ArrayList<>();
			for (IMendixObject obj : objs)
				result.add(workflowcommons.proxies.WorkflowSeries.initialize(context, obj));
		}
		return result;
	}
	public static java.util.List<system.proxies.WorkflowUserTask> dS_WorkflowTask(IContext context, workflowcommons.proxies.DashboardContext _dashboardContext)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("DashboardContext", _dashboardContext == null ? null : _dashboardContext.getMendixObject());
		java.util.List<IMendixObject> objs = Core.microflowCall("WorkflowCommons.DS_WorkflowTask").withParams(params).execute(context);
		java.util.List<system.proxies.WorkflowUserTask> result = null;
		if (objs != null)
		{
			result = new java.util.ArrayList<>();
			for (IMendixObject obj : objs)
				result.add(system.proxies.WorkflowUserTask.initialize(context, obj));
		}
		return result;
	}
	public static java.util.List<system.proxies.WorkflowUserTaskDefinition> dS_WorkflowTaskDefinition_Selectable_Administrator(IContext context, workflowcommons.proxies.DashboardContext _dashboardContext)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("DashboardContext", _dashboardContext == null ? null : _dashboardContext.getMendixObject());
		java.util.List<IMendixObject> objs = Core.microflowCall("WorkflowCommons.DS_WorkflowTaskDefinition_Selectable_Administrator").withParams(params).execute(context);
		java.util.List<system.proxies.WorkflowUserTaskDefinition> result = null;
		if (objs != null)
		{
			result = new java.util.ArrayList<>();
			for (IMendixObject obj : objs)
				result.add(system.proxies.WorkflowUserTaskDefinition.initialize(context, obj));
		}
		return result;
	}
	public static void oCh_DashboardContext_UpdateWorkflowDashboard(IContext context, workflowcommons.proxies.DashboardContext _dashboardContext)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("DashboardContext", _dashboardContext == null ? null : _dashboardContext.getMendixObject());
		Core.microflowCall("WorkflowCommons.OCh_DashboardContext_UpdateWorkflowDashboard").withParams(params).execute(context);
	}
	public static void oCl_WorkflowSummary(IContext context, workflowcommons.proxies.WorkflowSummary _workflowSummary)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("WorkflowSummary", _workflowSummary == null ? null : _workflowSummary.getMendixObject());
		Core.microflowCall("WorkflowCommons.OCl_WorkflowSummary").withParams(params).execute(context);
	}
	public static workflowcommons.proxies.DashboardContext sUB_DashboardContext_RetrieveOrCreate(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("WorkflowCommons.SUB_DashboardContext_RetrieveOrCreate").withParams(params).execute(context);
		return result == null ? null : workflowcommons.proxies.DashboardContext.initialize(context, result);
	}
	public static void sUB_DashboardContext_UpdateSettings(IContext context, workflowcommons.proxies.DashboardContext _dashboardContext)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("DashboardContext", _dashboardContext == null ? null : _dashboardContext.getMendixObject());
		Core.microflowCall("WorkflowCommons.SUB_DashboardContext_UpdateSettings").withParams(params).execute(context);
	}
	public static void sUB_TaskCount_Update(IContext context, workflowcommons.proxies.TaskCount _taskCount)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("TaskCount", _taskCount == null ? null : _taskCount.getMendixObject());
		Core.microflowCall("WorkflowCommons.SUB_TaskCount_Update").withParams(params).execute(context);
	}
	public static workflowcommons.proxies.TaskSummary sUB_TaskSummary_CreateOrUpdate(IContext context, workflowcommons.proxies.DashboardContext _dashboardContext, system.proxies.WorkflowDefinition _workflowDefinition_Selected, boolean _admin, system.proxies.WorkflowUserTaskDefinition _taskDefinition_Selected)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("DashboardContext", _dashboardContext == null ? null : _dashboardContext.getMendixObject());
		params.put("WorkflowDefinition_Selected", _workflowDefinition_Selected == null ? null : _workflowDefinition_Selected.getMendixObject());
		params.put("Admin", _admin);
		params.put("TaskDefinition_Selected", _taskDefinition_Selected == null ? null : _taskDefinition_Selected.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("WorkflowCommons.SUB_TaskSummary_CreateOrUpdate").withParams(params).execute(context);
		return result == null ? null : workflowcommons.proxies.TaskSummary.initialize(context, result);
	}
	public static workflowcommons.proxies.TaskSummary sUB_TaskSummary_RetrieveOrCreate(IContext context, workflowcommons.proxies.DashboardContext _dashboardContext)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("DashboardContext", _dashboardContext == null ? null : _dashboardContext.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("WorkflowCommons.SUB_TaskSummary_RetrieveOrCreate").withParams(params).execute(context);
		return result == null ? null : workflowcommons.proxies.TaskSummary.initialize(context, result);
	}
	public static administration.proxies.Account sUB_User_GetAccount(IContext context, system.proxies.User _user)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("User", _user == null ? null : _user.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("WorkflowCommons.SUB_User_GetAccount").withParams(params).execute(context);
		return result == null ? null : administration.proxies.Account.initialize(context, result);
	}
	public static void sUB_UserTask_Assign(IContext context, system.proxies.User _user, system.proxies.WorkflowUserTask _workflowUserTask)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("User", _user == null ? null : _user.getMendixObject());
		params.put("WorkflowUserTask", _workflowUserTask == null ? null : _workflowUserTask.getMendixObject());
		Core.microflowCall("WorkflowCommons.SUB_UserTask_Assign").withParams(params).execute(context);
	}
	public static java.lang.Long sUB_UserTask_CountFailed(IContext context, java.util.Date _completedAfter, java.util.Date _completedBefore, system.proxies.User _user, system.proxies.WorkflowDefinition _workflowDefinition_Selected, system.proxies.WorkflowUserTaskDefinition _taskDefinition_Selected)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("CompletedAfter", _completedAfter);
		params.put("CompletedBefore", _completedBefore);
		params.put("User", _user == null ? null : _user.getMendixObject());
		params.put("WorkflowDefinition_Selected", _workflowDefinition_Selected == null ? null : _workflowDefinition_Selected.getMendixObject());
		params.put("TaskDefinition_Selected", _taskDefinition_Selected == null ? null : _taskDefinition_Selected.getMendixObject());
		return (java.lang.Long) Core.microflowCall("WorkflowCommons.SUB_UserTask_CountFailed").withParams(params).execute(context);
	}
	public static java.lang.Long sUB_UserTask_CountInProgress(IContext context, java.util.Date _startedAfter, java.util.Date _startedBefore, system.proxies.WorkflowUserTaskDefinition _taskDefinition_Selected, system.proxies.User _user, system.proxies.WorkflowDefinition _workflowDefinition_Selected)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("StartedAfter", _startedAfter);
		params.put("StartedBefore", _startedBefore);
		params.put("TaskDefinition_Selected", _taskDefinition_Selected == null ? null : _taskDefinition_Selected.getMendixObject());
		params.put("User", _user == null ? null : _user.getMendixObject());
		params.put("WorkflowDefinition_Selected", _workflowDefinition_Selected == null ? null : _workflowDefinition_Selected.getMendixObject());
		return (java.lang.Long) Core.microflowCall("WorkflowCommons.SUB_UserTask_CountInProgress").withParams(params).execute(context);
	}
	public static java.lang.Long sUB_UserTask_CountOverdue(IContext context, java.util.Date _completedAfter, java.util.Date _completedBefore, system.proxies.WorkflowDefinition _workflowDefinition_Selected, system.proxies.User _user, system.proxies.WorkflowUserTaskDefinition _taskDefinition_Selected)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("CompletedAfter", _completedAfter);
		params.put("CompletedBefore", _completedBefore);
		params.put("WorkflowDefinition_Selected", _workflowDefinition_Selected == null ? null : _workflowDefinition_Selected.getMendixObject());
		params.put("User", _user == null ? null : _user.getMendixObject());
		params.put("TaskDefinition_Selected", _taskDefinition_Selected == null ? null : _taskDefinition_Selected.getMendixObject());
		return (java.lang.Long) Core.microflowCall("WorkflowCommons.SUB_UserTask_CountOverdue").withParams(params).execute(context);
	}
	public static java.math.BigDecimal sUB_Workflow_AverageHandlingTime(IContext context, java.lang.Long _workflow_CountCompleted, java.util.Date _completedAfter, java.util.Date _completedBefore, system.proxies.WorkflowDefinition _workflowDefinition_Selected)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Workflow_CountCompleted", _workflow_CountCompleted);
		params.put("CompletedAfter", _completedAfter);
		params.put("CompletedBefore", _completedBefore);
		params.put("WorkflowDefinition_Selected", _workflowDefinition_Selected == null ? null : _workflowDefinition_Selected.getMendixObject());
		return (java.math.BigDecimal) Core.microflowCall("WorkflowCommons.SUB_Workflow_AverageHandlingTime").withParams(params).execute(context);
	}
	public static void sUB_WorkflowDashboard_Update(IContext context, workflowcommons.proxies.DashboardContext _dashboardContext)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("DashboardContext", _dashboardContext == null ? null : _dashboardContext.getMendixObject());
		Core.microflowCall("WorkflowCommons.SUB_WorkflowDashboard_Update").withParams(params).execute(context);
	}
	public static workflowcommons.proxies.WorkflowSummary sUB_WorkflowSummary_CreateOrUpdate(IContext context, workflowcommons.proxies.DashboardContext _dashboardContext, system.proxies.WorkflowDefinition _workflowDefinition_Selected)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("DashboardContext", _dashboardContext == null ? null : _dashboardContext.getMendixObject());
		params.put("WorkflowDefinition_Selected", _workflowDefinition_Selected == null ? null : _workflowDefinition_Selected.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("WorkflowCommons.SUB_WorkflowSummary_CreateOrUpdate").withParams(params).execute(context);
		return result == null ? null : workflowcommons.proxies.WorkflowSummary.initialize(context, result);
	}
	public static workflowcommons.proxies.WorkflowSummary sUB_WorkflowSummary_RetrieveOrCreate(IContext context, workflowcommons.proxies.DashboardContext _dashboardContext)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("DashboardContext", _dashboardContext == null ? null : _dashboardContext.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("WorkflowCommons.SUB_WorkflowSummary_RetrieveOrCreate").withParams(params).execute(context);
		return result == null ? null : workflowcommons.proxies.WorkflowSummary.initialize(context, result);
	}
	public static java.lang.Long sUB_Worklow_CountCompletedOnTime(IContext context, java.util.Date _completedAfter, java.util.Date _completedBefore, system.proxies.WorkflowDefinition _workflowDefinition_Selected)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("CompletedAfter", _completedAfter);
		params.put("CompletedBefore", _completedBefore);
		params.put("WorkflowDefinition_Selected", _workflowDefinition_Selected == null ? null : _workflowDefinition_Selected.getMendixObject());
		return (java.lang.Long) Core.microflowCall("WorkflowCommons.SUB_Worklow_CountCompletedOnTime").withParams(params).execute(context);
	}
	public static java.lang.Long sUB_Worklow_CountCompletedOverdue(IContext context, java.util.Date _completedAfter, java.util.Date _completedBefore, system.proxies.WorkflowDefinition _workflowDefinition_Selected)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("CompletedAfter", _completedAfter);
		params.put("CompletedBefore", _completedBefore);
		params.put("WorkflowDefinition_Selected", _workflowDefinition_Selected == null ? null : _workflowDefinition_Selected.getMendixObject());
		return (java.lang.Long) Core.microflowCall("WorkflowCommons.SUB_Worklow_CountCompletedOverdue").withParams(params).execute(context);
	}
	public static java.lang.Long sUB_Worklow_CountInProgress(IContext context, java.util.Date _startedAfter, java.util.Date _startedBefore, system.proxies.WorkflowDefinition _workflowDefinition_Selected)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("StartedAfter", _startedAfter);
		params.put("StartedBefore", _startedBefore);
		params.put("WorkflowDefinition_Selected", _workflowDefinition_Selected == null ? null : _workflowDefinition_Selected.getMendixObject());
		return (java.lang.Long) Core.microflowCall("WorkflowCommons.SUB_Worklow_CountInProgress").withParams(params).execute(context);
	}
	public static java.lang.Long sUB_Worklow_CountOverdue(IContext context, java.util.Date _startedAfter, java.util.Date _startedBefore, system.proxies.WorkflowDefinition _workflowDefinition_Selected)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("StartedAfter", _startedAfter);
		params.put("StartedBefore", _startedBefore);
		params.put("WorkflowDefinition_Selected", _workflowDefinition_Selected == null ? null : _workflowDefinition_Selected.getMendixObject());
		return (java.lang.Long) Core.microflowCall("WorkflowCommons.SUB_Worklow_CountOverdue").withParams(params).execute(context);
	}
}