// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package filehandling.actions;

import java.awt.image.BufferedImage;
import javax.imageio.ImageIO;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import filehandling.proxies.ImageDimensions;

public class GetImageDimensions extends CustomJavaAction<IMendixObject>
{
	private IMendixObject __Image;
	private system.proxies.Image Image;

	public GetImageDimensions(IContext context, IMendixObject Image)
	{
		super(context);
		this.__Image = Image;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		this.Image = __Image == null ? null : system.proxies.Image.initialize(getContext(), __Image);

		// BEGIN USER CODE
		BufferedImage bimg = ImageIO.read(Core.getImage(getContext(), this.Image.getMendixObject(), false));
		ImageDimensions imageDimentions = new ImageDimensions(getContext());
		imageDimentions.setHeight(bimg.getHeight());
		imageDimentions.setWidth(bimg.getWidth());
		return imageDimentions.getMendixObject();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetImageDimensions";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
