// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package expenserequestexample.proxies.workflows;

import com.mendix.core.Core;
import com.mendix.workflows.WorkflowDefinition;

public final class Workflows
{
    /**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Workflows() {}

    // These are the workflows for the ExpenseRequestExample module
    public static WorkflowDefinition expenseRequest() 
    {
        return Core.workflows().getDefinition("ExpenseRequestExample.ExpenseRequest");
    }
    public static WorkflowDefinition parallelWorkflow() 
    {
        return Core.workflows().getDefinition("ExpenseRequestExample.ParallelWorkflow");
    }
    public static WorkflowDefinition subWorkflow() 
    {
        return Core.workflows().getDefinition("ExpenseRequestExample.SubWorkflow");
    }
}
