// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package taskqueuehelpers.proxies.constants;

import com.mendix.core.Core;

public final class Constants
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Constants() {}

	// These are the constants for the TaskQueueHelpers module

	/**
	* The size of the batches during the clean up for ProcessedTasks. Keeping the higher value may causes potential memory issues.
	*/
	public static java.lang.Long getDeleteBatchSize()
	{
		return (java.lang.Long)Core.getConfiguration().getConstantValue("TaskQueueHelpers.DeleteBatchSize");
	}

	/**
	* The completed processed tasks which are older than this value in hours would be deleted during cleanup.
	*/
	public static java.lang.Long getTasksCompletedOlderThanHours()
	{
		return (java.lang.Long)Core.getConfiguration().getConstantValue("TaskQueueHelpers.TasksCompletedOlderThanHours");
	}

	/**
	* The NonCompleted tasks which are older than this value in hours would be deleted during cleanup.
	*/
	public static java.lang.Long getTasksNonCompletedOlderThanHours()
	{
		return (java.lang.Long)Core.getConfiguration().getConstantValue("TaskQueueHelpers.TasksNonCompletedOlderThanHours");
	}
}