// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package datawidgets.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	// These are the constants for the DataWidgets module

	public static java.lang.String getDataWidgets_Version()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("DataWidgets.DataWidgets_Version");
	}
}