// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package workflowcommonsunittests.proxies.workflows;

import com.mendix.core.Core;
import com.mendix.workflows.WorkflowDefinition;

public final class Workflows
{
    /**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Workflows() {}

    // These are the workflows for the WorkflowCommonsUnitTests module
    public static WorkflowDefinition dummyWorkflow() 
    {
        return Core.workflows().getDefinition("WorkflowCommonsUnitTests.DummyWorkflow");
    }
}
